open-chat-labs/open-chat

backend/canisters/user_index/api/src/queries/c2c_lookup_principal.rs
backend/canisters/user_index/impl/src/model/user.rs
backend/canisters/user_index/impl/src/model/user_map.rs
backend/canisters/user_index/impl/src/queries/c2c_lookup_principal.rs
backend/canisters/user_index/impl/src/updates/register_user.rs
backend/libraries/types/can.did
backend/libraries/types/src/user_summary.rs

When creating a group we now query the user_index to verify that the caller is a valid OpenChat user.
This means the ProposalsBot needs to exist as a user in the user_index, otherwise it won't be able to create new groups.
This PR simply adds an `is_bot` field to each user record.
I'll create a follow on PR to register the ProposalsBot which will make use of that new field.

Add `is_bot` field to user records

---

backend/canisters/user_index/api/src/lifecycle/init.rs
backend/canisters/user_index/impl/src/lib.rs
backend/canisters/user_index/impl/src/lifecycle/init.rs
backend/libraries/canister_client/src/operations/install_service_canisters.rs

Up until now the ProposalsBot's user record has been hardcoded in the frontend and hasn't existed in the backend, but it now also needs to exist in the backend because we've started verifying users when they try to create groups.
So the ProposalsBot needs to be registered as a user when we initialize the service.

Register the ProposalsBot during user_index initialization

---

frontend/src/utils/caching.ts

I've tested this locally and can see it successfully clearing the users table. So this is now ready for review.

Only clear the `users` table in IndexedDb

---

frontend/src/components/home/CurrentChatMessages.svelte

The 'Go to bottom' button was only scrolling to the bottom of the currently loaded window, whereas it should always jump you to the latest message.

Scroll to latest message rather than bottom of window

---

frontend/src/components/home/CurrentChat.svelte
frontend/src/components/home/CurrentChatMessages.svelte
frontend/src/stores/markRead.ts

The unread message count was double counting in some scenarios because we now mark read from 0 -> N, meaning the server state could be 0 -> N _and_ the local state could be 0 -> N, and we weren't accounting for this when determining how many messages are unread.

Fix unread message count

---

frontend/src/components/home/CurrentChatMessages.svelte
frontend/src/components/home/Home.svelte
frontend/src/services/common/chatThread.ts
frontend/src/services/serviceContainer.ts
frontend/src/services/user/user.caching.client.ts
frontend/src/services/user/user.client.ts
frontend/src/services/userIndex/userIndex.caching.client.ts
frontend/src/services/userIndex/userIndex.client.ts
frontend/src/stores/chat.ts
frontend/src/stores/user.ts
frontend/src/utils/caching.ts
frontend/src/utils/userCache.ts

There are a few changes here:
1) staggering the loading of group details and previous events
2) splitting users into their own indexeddb since they rarely need to be ditched
3) vastly improve the efficiency of adding users to the user store (this makes by far the most difference)
Experimented with local storage which _is_ a good deal faster but a) it's sync and b) has limited capacity so isn't an ideal alternative.

a few changes to do with how users are loaded and cached

---

frontend/rollup.config.js
frontend/src/services/serviceContainer.ts
frontend/src/services/user/user.caching.client.ts
frontend/src/services/user/user.client.ts
frontend/src/services/userIndex/userIndex.caching.client.ts
frontend/src/services/userIndex/userIndex.client.ts
frontend/src/sw/index.ts
frontend/src/utils/userCache.ts

In addition to storing users in a separate indexeddb database, we will now attempt to do the bulk add in the service worker rather than in the main thread to further minimise the chance that it will interfere too much with the UI performance when large numbers of users need to be written to the cache.

set cached users via service worker

---

backend/integration_tests/Cargo.toml

This avoids building all of the integration test dependencies unnecessarily.

Speed up build by using `dev-dependencies`

---

frontend/app/rollup.config.js

If network type is "persistent", get from `canister_ids.json`, else get from `.dfx`.

Fix canister path for testnets

---

frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/stores/chat.ts

A follow on PR will move chat summary local updates into another store at which point we can make the `myServerChatSummaries` store private.

Move group previews into their own store

---

frontend/app/src/components/home/CryptoTransferBuilder.svelte
frontend/app/src/components/home/CurrentChat.svelte
frontend/app/src/components/home/thread/Thread.svelte

Before this PR, the default receiver was always based on who you were replying to in the main chat.
This PR ensures that if sending ICP within a thread, the receiver is defaulted to the user (if any) you are replying to in that thread.

Fix default receiver on ICP transfers

---

frontend/openchat-agent/src/worker.ts
frontend/openchat-client/src/agentWorker.ts

Seems like the error handling was _still_ not right. The actual handler function had the wrong signature and also (again) structuredClone seemed to be dropping some of the custom properties of the error so I have changed it to use JSON serialisation in the error case. 
It now logs us out correctly if we get that 403 error on start-up.

fix error handling

---

frontend/app/src/components/home/Home.svelte

Previously we returned early because the url path would be changed (removing the query string), causing `newChatSelected` to fire again.
But now the url doesn't change so we shouldn't exit early.

Fix landing on direct chat without query string

---

.vscode/settings.json
frontend/app/rollup.config.js
frontend/app/src/components/home/ImageContent.svelte
frontend/app/svelte.config.js

couple of people have complained about this and it seems easier (and fine) to just remove the caption when zoomed. 
Also getting rid of all those annoying a11y warnings that have come in with a new version of something or other.

remove image caption on zoom

---

frontend/app/src/components/App.svelte
frontend/app/src/components/register/Register.svelte

this fixes a regression that occurred when moving the landing page stuff. Referrals probably still working _most_ of the time, but we would not have been writing the code to local storage so would not have been bullet-proof.

make referral more robust

---

frontend/app/src/components/home/CurrentChatMessages.svelte
frontend/openchat-client/src/events.ts
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/stores/chat.ts
frontend/openchat-client/src/utils/chat.ts

So we will no longer load the latest event window when we send a message and we will not scroll to the bottom unless the events are up to date _and_ we are within the threshold. 
The complication was that we _also_ need to ensure that when we send a message we _do not_ append it to the server event store if doing so would lead to discontiguous ranges. 
fixes #2888

prevent scroll to bottom on send 

---

backend/canisters/group_index/impl/src/jobs/upgrade_canisters.rs
backend/canisters/local_user_index/impl/src/jobs/upgrade_canisters.rs
backend/canisters/notifications_index/impl/src/jobs/upgrade_canisters.rs

This will cause `upgrade_canisters` to be called roughly every other block which will reduce the cost without having much effect on the upgrade speed.

Add small delay between each `upgrade_canisters` invocation

---

frontend/app/src/components/home/Home.svelte

I have no clue (at the moment) why this is necessary and it wasn't before, but without this `tick` the computed properties that depend on `rightPanelHistory` do not update and everything goes wrong.

fix thread opening

---

frontend/CHANGELOG.md
frontend/app/src/components/home/ChatEvent.svelte
frontend/app/src/components/home/ChatMessage.svelte
frontend/app/src/components/home/ChatMessageMenu.svelte
frontend/app/src/components/home/thread/ThreadPreview.svelte

As discussed, hard to know whether this is really effective but it certainly prevents the constant firing of `afterUpdate` in the ChatMessage component.

reduce re-rendering

---

frontend/openchat-agent/src/utils/caching.ts

There is a new "deleted" field on a FE Message which gets cached. This will be falsey for all cached messages even those that have been deleted. This causes issues with viewing and undeleting deleted messages.

Bump cache version since field added to Message

---

backend/bots/examples/icp_dispenser/impl/src/lifecycle/init.rs
backend/bots/examples/icp_dispenser/impl/src/lifecycle/post_upgrade.rs
backend/bots/examples/sns1_airdrop/impl/src/lifecycle/init.rs
backend/bots/examples/sns1_airdrop/impl/src/lifecycle/post_upgrade.rs
backend/canisters/group/impl/src/lifecycle/init.rs
backend/canisters/group/impl/src/lifecycle/post_upgrade.rs
backend/canisters/group_index/impl/src/lifecycle/init.rs
backend/canisters/group_index/impl/src/lifecycle/post_upgrade.rs
backend/canisters/local_group_index/impl/src/lifecycle/init.rs
backend/canisters/local_group_index/impl/src/lifecycle/post_upgrade.rs
backend/canisters/local_user_index/impl/src/lifecycle/init.rs
backend/canisters/local_user_index/impl/src/lifecycle/post_upgrade.rs
backend/canisters/notifications/impl/src/lifecycle/init.rs
backend/canisters/notifications/impl/src/lifecycle/post_upgrade.rs
backend/canisters/notifications_index/impl/src/lifecycle/init.rs
backend/canisters/notifications_index/impl/src/lifecycle/post_upgrade.rs
backend/canisters/online_users/impl/src/lifecycle/init.rs
backend/canisters/online_users/impl/src/lifecycle/post_upgrade.rs
backend/canisters/proposals_bot/impl/src/lifecycle/init.rs
backend/canisters/proposals_bot/impl/src/lifecycle/post_upgrade.rs
backend/canisters/user/impl/src/lifecycle/init.rs
backend/canisters/user/impl/src/lifecycle/post_upgrade.rs
backend/canisters/user_index/impl/src/lifecycle/init.rs
backend/canisters/user_index/impl/src/lifecycle/post_upgrade.rs

These aren't needed because the cdk calls `setup` at the start of the code output by each of the cdk macros.
https://github.com/dfinity/cdk-rs/blob/0ee7a3c630fb635b8c8a843317d68d439f4a5408/src/ic-cdk-macros/src/export.rs#L200

Remove calls to `ic_cdk::setup`

---

frontend/openchat-agent/src/services/openchatAgent.ts
frontend/openchat-agent/src/utils/caching.ts

This PR makes 2 changes
1 - Only write to the cache if there have been any updates
2 - Don't write latest messages taken from the chat summaries to the cache, since the `cachePrimer` already get the latest events for any updated chats and writes them to the cache. Prior to the commit, the latest messages would be overwritten on every updates loop, which is unnecessary.

Improved cache handling

---

frontend/app/src/components/home/ChatEventList.svelte
frontend/app/src/components/home/ChatMessage.svelte
frontend/app/src/components/home/CurrentChatMessages.svelte
frontend/app/src/components/home/thread/Thread.svelte

If you choose to chat with a thread participant from their profile we were not closing the thread. Also noticed a possible case were recursion in `scrollToMessageIndex` would not terminate if the chat changes during the recursion.

couple of fixes for closing thread

---

frontend/app/src/components/home/ChatEventList.svelte
frontend/app/src/components/home/Home.svelte
frontend/app/src/components/home/RightPanel.svelte
frontend/app/src/components/home/thread/Thread.svelte
frontend/app/src/utils/urls.ts
frontend/openchat-client/src/agentWorker.ts
frontend/openchat-client/src/liveState.ts
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/stores/chat.ts
frontend/openchat-push/src/index.ts
frontend/openchat-shared/src/domain/chat/chat.ts

Make sure that urls of the form `/chat-id/message-index/thread-message-index` will open the thread and go to the right thread message. 
Make sure that notifications for thread message form the right url. 
fixes #2989

Fix thread routing

---

frontend/app/src/components/home/ChatEventList.svelte

This one weird trick makes scrolling to bottom work on iOS. There is obviously some odd timing issue. This is a bit distasteful but it seems to work everywhere with this.

reintroduce the weird retry loop

---

frontend/app/src/components/home/ChatEventList.svelte
frontend/app/src/components/home/ReminderBuilder.svelte

The way scrollToMessageIndex currently works is that it looks for the message's dom element and if it doesn't find it it tries to load it and then recurses. 
This can lead to infinite recursion if the message is _hidden_ because even after the message is loaded, the dom element will still not exist. 
Therefore, when we don't find the DOM element, before we recurse, we check whether we have already loaded the message. If we have already loaded it then there is no point recursing. We still can't scroll to the message because it's not there, but recursion is futile at that point so we just scroll to the bottom (which may not be idea - but there isn't really anything better we can do).

correct the infinite loop problem

---

frontend/openchat-client/src/openchat.ts

There's not much point in freezing a group if you can still see all of the messages.

prevent preview of frozen groups

---

frontend/openchat-client/src/stores/markRead.ts

This should deal with the problem that previewed chats are contributing incorrectly to the unread chat count.

return 0 unread messages for any unknown chat

---

frontend/openchat-agent/src/services/openchatAgent.ts

Even if there are no updates, we should overwrite the cache to increment the `latestActiveGroupsCheck` timestamp, otherwise we'll keep polling groups unnecessarily due to using an old timestamp.

Update cache after each updates loop

---

frontend/app/src/components/Router.svelte

it will assume that all legacy routes are group chats which is a lot better than nothing and probably accounts for the vast majority. I might try to do something that addresses direct chats separately.

95% fix for legacy routes

---

frontend/openchat-agent/src/services/candidService.ts
frontend/openchat-agent/src/services/error.ts
frontend/openchat-shared/src/domain/error.ts

We might get DestinationInvalid if a group has been delete for example. In this case there is no point in retrying, it's better to fail fast.

break out of retry loop on DestinationInvalid

---

frontend/app/src/components/Button.svelte
frontend/app/src/components/home/PollAnswer.svelte
frontend/app/src/components/home/PrizeContent.svelte
frontend/app/src/components/home/TextContent.svelte
frontend/app/src/components/home/Tweet.svelte
frontend/app/src/components/home/proposals/ProposalVoteButton.svelte

in iOS in safari if a parent element has a :hover pseudo selector and a descendent is clicked, the click handler does not fire first time. The first tap will trigger the parent hover state and only a second tap will activate the button. 
To prevent this weird behaviour I'm converting touchstart to click for certain elements where we know this is a problem. 
This is not a great solution. A better solution would be to replace all hover interactions with explicit taps or long presses on touch devices. But that will need a bit more testing so this seems a safer short term hacklet.

prevent ios problems with clicks inside hoverables

---

frontend/app/src/components/App.svelte
frontend/app/src/components/home/CurrentChat.svelte
frontend/app/src/components/home/Home.svelte
frontend/openchat-agent/src/utils/caching.ts
frontend/openchat-client/src/openchat.ts

support delete channel message for platform operator
close right panel when importing or converting a community
ensure that cache primer operates on _all_ chats rather than just the chats for the selected scope
bump cache since some people will probably have got into a weird state

some small bugs

---

backend/canisters/group_index/CHANGELOG.md
backend/canisters/group_index/impl/src/model/public_communities.rs
backend/libraries/types/can.did
backend/libraries/types/src/group_match.rs

There's something odd about the explore communities ordering but (local) unit tests seem fine so want to see the scores with prod data.

Add score to CommunityMatch

---

backend/canisters/group/CHANGELOG.md
backend/canisters/group/impl/src/lib.rs

This reverts commit 8ab4d3be3c948ca23b592a8646f9f61e0e604b13.

Revert "Discard old serialized state for the OpenChat group (#4093)"

---

frontend/app/package.json
frontend/app/src/components/QRCode.svelte
frontend/app/src/components/home/AccountInfo.svelte
frontend/app/src/components/home/InviteUsersWithLink.svelte
frontend/app/src/components/home/UserReferralCardContent.svelte
frontend/app/src/components/home/profile/ReferUsers.svelte
frontend/package-lock.json

Also, token QR codes now have a clear background around the token symbol.

Switch from using `svelte-qr` to `svelte-qrcode-image`

---

frontend/app/src/actions/longpress.ts
frontend/app/src/components/home/ChatEventList.svelte
frontend/app/src/stores/scrollPos.ts
frontend/openchat-client/src/utils/chat.ts

only activate the long press if we are more than 750ms away from the last scroll. This _feels_ about the right duration to avoid accidental activation without compromising deliberate activation. Only enabling this behaviour for Android since iOS seems to behave fine already.

Longpresss

---

frontend/app/src/components/home/profile/UserProfile.svelte

This gets immediately set to the correct value inside the relevant child component anyway it's just a different default that prevents the transient flicker of the invalid state.

assume valid rather than invalid

---

backend/canisters/group_index/CHANGELOG.md
backend/canisters/group_index/impl/src/lifecycle/inspect_message.rs

Previously I had added `set_max_concurrent_community_canister_upgrades` to inspect message but not `set_community_upgrade_concurrency`!

Accept calls to set_community_upgrade_concurrency

---

frontend/app/src/components/home/MentionPicker.svelte
frontend/app/src/components/home/SingleUserSelector.svelte

1. This fixes an issue where you can select @everyone or @usergroup as recipient of a crypto transfer
2. When selecting a recipient for a crypto transfer I was typing @ and expecting to see a list of users (and started debugging) before I realised that you don't start with @ at all. I have changed it so you now *can* start with @

Only allow users to be selected for crypto message

---

frontend/app/src/components/home/PrizeWinnerContent.svelte
frontend/app/src/components/home/profile/AccountsModal.svelte

+ unbreak the wallet modal footer.

allow winner messages to wrap where necessary

---

frontend/app/src/components/App.svelte

Turns out that this is the lesser of two evils. Without this safari will auto zoom when we focus text boxes and then stay zoomed which is terrible.

set max-scale for iOS

---

frontend/app/src/components/home/Footer.svelte
frontend/app/src/components/home/MessageActions.svelte
frontend/app/src/components/home/MessageEntry.svelte
frontend/app/src/components/home/RepliesTo.svelte
frontend/app/src/components/home/ReplyingTo.svelte

Trying to make slightly better use of vertical space by: 
* always limit the max height of replies (and replying-z)
* allow the message entry text box itself to expand to half the height of the screen
* refactor the inline emoji-picker to be a modal so that it overlays other components rather than stacking above
I _think_ this is an improvement. 
fixes #4833

rejig message entry layout a bit

---

frontend/app/src/components/home/ChatList.svelte

This stops us getting the wrong avatar transiently on the chat avatar when you change community. 
On the downside, you now get a blank avatar transiently sometimes which is also a bit puzzling. But having a key on the each is probably a good idea anyway.

add a key to the chat list #each

---

frontend/app/src/i18n/cn.json
frontend/app/src/i18n/de.json
frontend/app/src/i18n/en.json
frontend/app/src/i18n/es.json
frontend/app/src/i18n/fr.json
frontend/app/src/i18n/it.json
frontend/app/src/i18n/iw.json
frontend/app/src/i18n/jp.json
frontend/app/src/i18n/ru.json
frontend/app/src/i18n/vi.json

This reverts commit 2074f22f3b053955501087d85b33aa6512e7d326.
We need to wait until communities/groups are upgraded before changing the FE messaging

Revert "Adjust messaging for change of SNS pay gate fee % (#4995)"

---

frontend/app/src/components/Translatable.svelte

There are some cases where it is not that easy to tell whether a string was originally a resource key or just a hard-coded string (or a data value). The easiest way to make sure that we don't allow these to be "corrected" is to double check that they are actually translatable values (i.e. they exist in the i18n dictionary).

prevent hard-coded strings appearing as translatable

---

backend/canisters/local_user_index/CHANGELOG.md
backend/canisters/local_user_index/api/src/updates/register_user.rs
backend/canisters/local_user_index/impl/src/updates/register_user.rs
backend/canisters/user_index/CHANGELOG.md
backend/canisters/user_index/api/src/lib.rs
backend/canisters/user_index/impl/src/updates/c2c_notify_events.rs
backend/integration_tests/src/client/identity.rs
backend/integration_tests/src/lib.rs
backend/integration_tests/src/rng.rs

This allows us to differentiate between the old principals which are derived from II and the new principals which are derived from the new Identity canister.

Add `is_from_identity_canister` to `UserRegistered` events

---

scripts/download-canister-wasm.sh

This makes it download the latest available wasm rather than using the latest commit (which may still be building).

Fix `download-canister-wasm.sh` script

---

frontend/app/src/components/home/communities/explore/Explore.svelte
frontend/app/src/stores/search.ts

It's really annoying if you scroll down the list of communities and click on one and then go back and you have lost your place and have to start again. 
This keeps the results in a store and also preserves your scroll position. 
fixes #5184

persist community search results

---

frontend/app/src/components/home/ChatEventList.svelte
frontend/app/src/components/home/ChatMessage.svelte

When the size of the scrollable container changes due to the addition of more content (when loading new messages in either scroll direction), we sometimes need to intervene to maintain a consistent perceived scroll position. Finding precisely the right point in time to make this adjustment has always been problematic and previously we have tried to use the svelte lifecycle to pick the right moment. 
This is a new approach that uses a mutation observer that will fire if changes in the target (or its subtree) cause the target's scrollHeight to change. 
This _appears_ to result in more reliable adjustments and fewer (if any) unexpected leaps in scroll position when loading dynamic content.

Change the way scroll position is managed when adding dynamic content

---

frontend/app/src/components/App.svelte
frontend/app/src/components/home/video/ActiveCall.svelte
frontend/openchat-client/src/openchat.ts
frontend/openchat-shared/src/utils/notifications.ts

So that we are not completely reliant on a working webrtc connection for this to work. It still won't be bulletproof but it seems to work.

trigger the incoming call modal from push notification as well

---

frontend/app/src/components/FindUser.svelte
frontend/app/src/components/home/ChatListSearch.svelte
frontend/app/src/components/home/communities/details/UserGroup.svelte
frontend/app/src/components/home/groupdetails/Members.svelte
frontend/app/src/utils/user.ts

Some people (myself included) have tried to search for users by starting with the @ symbol but the only time that works, and is in fact necessary, is when searching for messages by username. This PR disregards a leading @ when searching for users.
This is on webtest

Ignore leading @ symbol when searching for users

---

frontend/app/src/components/home/ChatMessage.svelte
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/utils/chat.ts
frontend/openchat-client/src/utils/rtcConnectionsManager.ts

This creates a connection with either a prefix of `m_` or `d_` depending on whether we are using mobile or desktop. Then when we try to connect to another user we try to connect to both the `m_` and `d_` variant. 
This should allow us to use both phone and desktop at the same time and have rtc connections in both cases. 
_Seems_ to work but could do with a bit of testing on webtest before we commit to it.

Device level rtc connections

---

frontend/app/src/components/home/Home.svelte
frontend/app/src/components/home/LeftPanel.svelte
frontend/app/src/components/home/MiddlePanel.svelte
frontend/app/src/components/home/communities/explore/Explore.svelte
frontend/app/src/components/home/nav/BottomNav.svelte
frontend/app/src/components/home/nav/CommonNavElements.svelte
frontend/app/src/components/home/nav/LeftNav.svelte
frontend/app/src/components/home/nav/NavItem.svelte
frontend/app/src/stores/layout.ts

This is more consistent with other similar mobile apps and makes important navigations easier to reach with the thumb. 
This will also free up some space in the left nav on mobile for streak / chit related CTA.

add footer tray for mobile view

---

frontend/app/src/components/home/profile/Accounts.svelte
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/utils/location.ts

This does a few things: 
* introduces a new api to try _before_ we try the existing api
* adds a retry mechanism for the overall process
* requests country code only on demand when the user attempts to use the swap feature (in case we have some sort of rate limiting problem).

Fix geo location

---

backend/canisters/user/CHANGELOG.md
backend/canisters/user/impl/src/lifecycle/post_upgrade.rs
backend/canisters/user/impl/src/timer_job_types.rs
backend/canisters/user/impl/src/updates/swap_tokens.rs

During the NNS subnet incident on Friday 14th the ICP ledger was unavailable for some of the time. There is some evidence that if a user was swapping to ICP during this time, ICPSwap might see their balance as zero and fail to deposit or withdraw the funds.
For an example see this user's canister logs at timestamp 1718396682164:
https://2enzf-kyaaa-aaaaf-avdva-cai.raw.icp0.io/logs
Also see the transaction history of ICP transferred into their account shows no record on the Friday so the withdrawal definitely failed:
https://dashboard.internetcomputer.org/transactions?p=7&m=12439383&t=259&to=550b8e0b7f5291b84cdd8c196f90c0756a2eb66f2ed79be378e5d550ea9380b3

Retry unfinished ICPSwaps + some extra logging

---

frontend/app/src/components/home/ChatList.svelte
frontend/app/src/components/home/communities/CommunityMenu.svelte
frontend/app/src/components/home/communities/DirectChatsHeader.svelte
frontend/app/src/components/home/communities/FavouriteChatsHeader.svelte
frontend/app/src/components/home/communities/GroupChatsHeader.svelte
frontend/app/src/components/home/communities/GroupChatsMenu.svelte
frontend/app/src/components/home/communities/SelectedCommunityHeader.svelte
frontend/app/src/i18n/en.json
frontend/app/src/styles/mixins.scss
frontend/openchat-client/src/openchat.ts

This one has been asked for a few times in the past.

mark all as read for all chats in a scope

---

backend/canisters/user_index/impl/src/model/user.rs

This fixes an issue with the already merged user_index PR. This needs to go in before we release the user_index for the first time.

Fix ser/de of user in user_index

---

frontend/app/src/components/MatchingUser.svelte
frontend/app/src/components/SelectChatModal.svelte
frontend/app/src/components/home/ChatList.svelte
frontend/app/src/components/home/ChatMessage.svelte
frontend/app/src/components/home/ChatSummary.svelte
frontend/app/src/components/home/CurrentChatHeader.svelte
frontend/app/src/components/home/DailyChitModal.svelte
frontend/app/src/components/home/profile/ChitEvents.svelte
frontend/app/src/components/home/profile/ReferUsers.svelte
frontend/app/src/components/home/profile/ViewUserProfile.svelte
frontend/openchat-agent/src/services/openchatAgent.ts
frontend/openchat-agent/src/utils/caching.ts
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/stores/global.ts
frontend/openchat-shared/src/domain/chat/chat.ts

One thing to note is that the streak value will not _itself_ be reactive with this approach. I think this will not cause a problem in practice, but if it does we can pass in one of the $now stores.

Calculate streak on demand for the current user

---

frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/utils/credentials.ts

Verified credentials are currently broken on live. Since not sure exactly when we will get the composite gates stuff out, this is worth cherry picking out to fix it.

fix vc structure

---

frontend/openchat-agent/src/services/community/candid/idl.js
frontend/openchat-agent/src/services/community/candid/types.d.ts
frontend/openchat-agent/src/services/community/mappers.ts
frontend/openchat-agent/src/services/group/candid/types.d.ts
frontend/openchat-agent/src/services/groupIndex/candid/types.d.ts
frontend/openchat-agent/src/services/localUserIndex/candid/types.d.ts
frontend/openchat-agent/src/services/notifications/candid/types.d.ts
frontend/openchat-agent/src/services/online/candid/types.d.ts
frontend/openchat-agent/src/services/proposalsBot/candid/types.d.ts
frontend/openchat-agent/src/services/registry/candid/types.d.ts
frontend/openchat-agent/src/services/storageBucket/candid/types.d.ts
frontend/openchat-agent/src/services/storageIndex/candid/types.d.ts
frontend/openchat-agent/src/services/translations/candid/types.d.ts
frontend/openchat-agent/src/services/user/candid/idl.js
frontend/openchat-agent/src/services/user/candid/types.d.ts
frontend/openchat-agent/src/services/user/mappers.ts
frontend/openchat-agent/src/services/userIndex/candid/idl.js
frontend/openchat-agent/src/services/userIndex/candid/types.d.ts
frontend/openchat-agent/src/services/userIndex/mappers.ts
frontend/openchat-agent/src/services/userIndex/userIndex.client.ts
frontend/openchat-agent/src/utils/userCache.ts
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/stores/user.ts
frontend/openchat-shared/src/domain/chit.ts
frontend/openchat-shared/src/domain/community/index.ts
frontend/openchat-shared/src/domain/response.ts
frontend/openchat-shared/src/domain/user/user.ts

When we request user summaries we may get back a list of deleted userIds now. 
We now cache the deleted userIds so that we can a) populate the userstore with dummy deleted users (to prevent and crashes) and b) remove any deleted users from subsequent requests for updated users (we were seeing around 100 of these every time the OC community is selected.

Integrate deleted users into the getUsers response

---

frontend/openchat-client/src/openchat.ts

CLS wanted (hashed) email and wallet, but we don't always have that and the underlying requirement is something unique to the user so this should do.

capture userID in the registerUser tracking

---

frontend/app/src/components/landingpages/FeaturesPage.svelte

this blatantly should not have compiled. Still don't understand why the compiler didn't catch it.

fix features page

---

backend/canisters/community/CHANGELOG.md
backend/canisters/community/api/src/updates/mod.rs
backend/canisters/community/impl/src/regular_jobs.rs
backend/canisters/community/impl/src/updates/c2c_migrate_events_to_stable_memory.rs
backend/canisters/community/impl/src/updates/mod.rs
backend/canisters/group/CHANGELOG.md
backend/canisters/group/impl/src/updates/c2c_migrate_events_to_stable_memory.rs
backend/canisters/user/CHANGELOG.md

This reverts commit ce452a958955d20da860d229d416fef10d6dbada.

Revert "Remove event migration job from communities (#6751)"

---

frontend/openchat-shared/src/utils/chat.ts

Seeing multiple instances of "Unknown" user claiming prizes has caused a bit of confusion and caused some conspiracy theories - this should fix it.

Rehydrate prize winner users

---

frontend/openchat-client/src/openchat.ts
frontend/openchat-shared/src/domain/chat/chat.ts
frontend/package-lock.json
frontend/package.json

Allows us to edit anything editable and captioned without losing the main content. This only worked for attachment content types before.

fix the way edit message works

---

backend/canisters/user_index/impl/src/model/user_map.rs
backend/canisters/user_index/impl/src/queries/mod.rs
backend/integration_tests/src/lib.rs

This reverts commit 36cae095ad062e38feab58f794e1f22ff0fd9179.

Revert "Temporarily comment out bot endpoints to reduce size below limit (#7100)"

---

backend/canisters/local_user_index/CHANGELOG.md
backend/canisters/local_user_index/impl/src/updates/execute_bot_command.rs
backend/integration_tests/src/client/local_user_index.rs
backend/integration_tests/src/diamond_membership_tests.rs
backend/libraries/jwt/src/lib.rs

This will resolve the failing integration test

Fix unit of claims expiry

---

frontend/app/src/components/bots/BotMessageContext.svelte
frontend/app/src/components/home/ChatEvent.svelte
frontend/app/src/components/home/ChatMessage.svelte
frontend/app/src/components/home/thread/ThreadPreview.svelte
frontend/openchat-agent/src/services/common/chatMappersV2.ts
frontend/openchat-agent/src/services/externalBot/externalBot.ts
frontend/openchat-agent/src/services/openchatAgent.ts
frontend/openchat-client/src/openchat.ts
frontend/openchat-shared/src/domain/bots.ts
frontend/openchat-shared/src/domain/chat/chat.ts
frontend/openchat-shared/src/domain/worker.ts
frontend/openchat-worker/src/worker.ts

Steps towards handling bot response messages on the client. 
This decodes a success response from the bot which _may_ contain a message content. This is then treated as an unconfirmed message from the bot user which gives quite a nice user experience.

Bot message rendering

---

frontend/app/src/components/home/ChatMessage.svelte

Added rule to break strings that have many characters, when chat bubble is on the smaller size due to width constrictions.

Break longer-than-message-bubble strings

---

backend/integration_tests/src/communities/access_gate_expiry_tests.rs

These tests show that diamond members of a group/community/channel with a diamond gate do not lapse when the gate expires (unless their membership expires).

Test expiring diamond gate

---

frontend/app/src/components/home/ChatMessage.svelte

Moved the word-break rule to the markdown wrapper, which should limit the effect, and fix the issue with the proposal bubble.

Fix proposal bubble

---

backend/notification_pusher/core/src/lib.rs
backend/notification_pusher/core/src/metrics.rs
backend/notification_pusher/core/src/processor.rs
backend/notification_pusher/core/src/pusher.rs
backend/notification_pusher/core/src/reader.rs

We now have 1 `reader` thread per notifications canister which pulls in new notifications every second and puts them into a queue.
Then we have a `processor` thread which consumes that queue and synchronously builds the individual web push messages.
Then we have multiple `pusher` threads which pull notifications off the queue and push them.

Move notification processing to single synchronous thread + more metrics

---

frontend/app/src/components/home/TruncatedAccount.svelte
frontend/app/src/components/home/profile/LinkedAuthAccounts.svelte

A few users have copied these principals and then sent funds to them.
There are no use cases where a user needs these principals in full so we should remove the ability to copy them.

Prevent copying sign in principals

---

backend/canisters/community/CHANGELOG.md
backend/canisters/community/impl/src/updates/edit_message.rs
backend/canisters/community/impl/src/updates/send_message.rs
backend/canisters/group/CHANGELOG.md
backend/canisters/group/impl/src/updates/edit_message.rs
backend/canisters/group/impl/src/updates/send_message.rs
backend/canisters/user/CHANGELOG.md
backend/canisters/user/impl/src/updates/c2c_notify_user_canister_events.rs
backend/canisters/user/impl/src/updates/c2c_send_messages.rs
backend/canisters/user/impl/src/updates/edit_message.rs
backend/canisters/user/impl/src/updates/send_message.rs
backend/libraries/chat_events/src/chat_events.rs
backend/libraries/chat_events/src/message_content_internal.rs
backend/libraries/group_chat_core/src/lib.rs
backend/libraries/types/src/message_content.rs

The goal here is to eventually make it only possible to create `MessageContentInternal` instances by calling the validation function. This will make it impossible to create instances without them being validated.
This by separating the validation from the message sending we take a step towards supporting messages containing ICRC2 transfers from bots. In those cases we will perform validation, then process any ICRC2 transfers, then finally send the message.

Move new message validation to `MessageContentInternal`

---

frontend/app/src/components/home/GenericPreview.svelte

In case of the image links relayed from discord, fetching their metadata returns incomplete data, with only `title = ""`. This in turn indicates to the component that preview should be rendered since at least one thing is there since `"" !== undefined`.
This PR adds a check to make sure that something is there for the `LinkInfo`, and if it is, then render the previews fully or partially.
Before
After

Do not render previews if no LinkInfo is provided

---

frontend/app/src/components/home/DailyChitModal.svelte

Show higher badges when applicable on the daily claim modal

---

frontend/openchat-client/src/utils/cachePrimer.ts

If a channel gets queued up in the cache primer, but then you leave the community before the channel is processed, then when the cache primer processes the channel the `const localUserIndex = this.localUserIndex(next);` throws an error, but the channel still remains as the next item to process.
So on the next iteration the channel is picked up again, and again it will fail, and so on.

Avoid infinite loop in cache primer if you leave community

---

frontend/app/src/components/home/MultiLineInput.svelte

Updated CSS for the multiline input field to break into new lines.

Fix for multiline input not breaking lines

---

backend/canisters/local_user_index/impl/src/updates/c2c_notify_user_index_events.rs
backend/canisters/user/api/src/lib.rs

The version of the User canisters which is live is still expecting the `token` field, so I have added it back in as optional so that it gets populated for now but can easily be removed after the next upgrade.

Fix pushing diamond membership payment events

---

backend/canisters/community/CHANGELOG.md
backend/canisters/community/impl/src/updates/create_channel.rs
backend/canisters/user/impl/src/updates/create_community.rs
backend/libraries/chat_events/src/chat_events.rs
backend/libraries/group_chat_core/src/lib.rs
backend/libraries/utils/src/text_validation.rs

Previously we blocked any channels that contained the text "proposals".
This restriction still applies to groups but has been removed from channels.

Loosen channel name restrictions

---

frontend/app/src/components/home/profile/AccountTransactions.svelte

Currently approvals look like regular transactions so it appears as if you're double spending.
We could potentially improve this to show them but highlight the fact that they are approvals, but for now I think removing them is a good improvement.

Filter out approvals when displaying transaction history

---

frontend/app/src/components/home/ChatEventList.svelte
frontend/app/src/components/home/CurrentChatMessages.svelte
frontend/openchat-client/src/stores/chat.ts
frontend/openchat-client/src/stores/index.ts
frontend/openchat-client/src/stores/setStore.ts

This covers the case where too many (or even _all_) events are filtered out from the initial load. This would then wait for the next iteration of the update loop to go and load more giving the impression that the chat was really slow to load. 
We also add an equality check to the set store. This stops some unnecessary re-computation of derived state that can have some big knock on effects.

correct a couple of performance issues

---

frontend/openchat-client/src/openchat.ts

This makes a two improvements -
- It returns early without joining the semaphore's queue if the value is already cached
- It avoids sending duplicate requests for the same token if there is already a request in flight
This is needed because as token balances are updated, the tokens are re-ordered which makes the components re-render which in turn causes them to refresh their balances again.
Without this change this would result in multiple queries being made in parallel for the same token.

Avoid sending any duplicate requests when refreshing all balances

---

backend/canisters/community/impl/src/updates/change_role.rs
backend/canisters/community/impl/src/updates/delete_messages.rs
backend/canisters/community/impl/src/updates/remove_member.rs
backend/canisters/group/impl/src/updates/change_role.rs
backend/canisters/group/impl/src/updates/convert_into_community.rs
backend/canisters/group/impl/src/updates/delete_messages.rs
backend/canisters/group/impl/src/updates/remove_participant.rs
backend/canisters/group_index/impl/src/updates/add_hot_group_exclusion.rs
backend/canisters/group_index/impl/src/updates/delete_frozen_group.rs
backend/canisters/group_index/impl/src/updates/freeze_community.rs
backend/canisters/group_index/impl/src/updates/freeze_group.rs
backend/canisters/group_index/impl/src/updates/mark_local_group_index_full.rs
backend/canisters/group_index/impl/src/updates/set_community_moderation_flags.rs
backend/canisters/group_index/impl/src/updates/set_community_upgrade_concurrency.rs
backend/canisters/group_index/impl/src/updates/set_group_upgrade_concurrency.rs
backend/canisters/local_user_index/c2c_client/src/lib.rs
backend/canisters/market_maker/impl/src/updates/update_config.rs
backend/canisters/proposals_bot/impl/src/updates/stake_neuron_for_submitting_proposals.rs
backend/canisters/proposals_bot/impl/src/updates/submit_proposal.rs
backend/canisters/proposals_bot/impl/src/updates/top_up_neuron.rs
backend/canisters/registry/impl/src/updates/add_message_filter.rs
backend/canisters/registry/impl/src/updates/add_remove_swap_provider.rs
backend/canisters/registry/impl/src/updates/remove_message_filter.rs
backend/canisters/registry/impl/src/updates/set_airdrop_config.rs
backend/canisters/registry/impl/src/updates/set_token_enabled.rs
backend/canisters/translations/impl/src/queries/proposed.rs
backend/canisters/translations/impl/src/updates/approve.rs
backend/canisters/translations/impl/src/updates/propose.rs
backend/canisters/translations/impl/src/updates/reject.rs
backend/canisters/user_index/c2c_client/src/lib.rs

This opens the doors for follow on changes where it integrates nicer with the new `OCError` and `OCResult` response types.
Eg. if a function is returning `OCResult` we can simply do `lookup_user(..)?;`

Simplify `lookup_user` return type

---

backend/canisters/community/CHANGELOG.md
backend/canisters/group/CHANGELOG.md
backend/canisters/user/CHANGELOG.md
backend/libraries/chat_events/src/chat_events.rs
backend/libraries/error_codes/src/lib.rs
backend/libraries/types/src/p2p_swaps.rs

This will allow us to update the status on the UI based on the error code

Use more fine grained error codes for P2P swaps

---

frontend/app/src/components/home/Markdown.svelte
frontend/app/src/utils/domPurify.ts

This will make it possible to embed images inside messages with markdown like this: 
Which is cool!

make github markdown image links work

---

frontend/openchat-agent/src/services/common/chunked.ts

Previously we would only retry once with a smaller chunk size, now we keep trying smaller chunk sizes until the chunk size is under 50 at which point we fail if the response is still too large.

Retry with smaller chunk size when loading events if response too large

---

frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/state/chat_details/merged.svelte.ts
frontend/openchat-client/src/state/chat_details/server.svelte.ts
frontend/openchat-client/src/stores/chat.ts

Previously the `isContiguous` checks weren't checking the chatId still matched which resulted in warnings being logged when attempting to add events to a no longer selected chat.
This PR also changes it such that we always run the various tasks on events, such as marking things read if current user was the sender, or bumping the latest message in the chat summary, whereas before these were skipped if the events were not contiguous.

Fix `isContiguous` checks and avoid exiting early when processing events

---

.github/workflows/backend.yaml
.github/workflows/setup-rust/action.yml

This should fix the failing `build-caches` action + avoids duplicating the installation step

Install additional required libs within `setup-rust` action

---

frontend/app/src/components/home/LinkPreviews.svelte
frontend/app/src/components/home/SpotifyPreview.svelte
frontend/app/src/components/home/YouTubePreview.svelte
frontend/app/src/components/home/communities/details/BrowseChannels.svelte

Hard to believe that we weren't already doing this. This can cause channels with lots of youtube videos in particular to crash. 
Secondary issue to be followed up - is there a better / more efficient / more recommended way to embed youtube links that _doesn't_ cause the site to crash.

make sure spotify & youtube previews use the intersection observer

---

backend/canisters/group_index/CHANGELOG.md
backend/canisters/group_index/impl/src/lifecycle/post_upgrade.rs
backend/canisters/group_index/impl/src/model/local_group_index_map.rs

This reinstates the logic to push Group/Community wasms to each LocalUserIndex in `post_upgrade` but this time bumps each wasm version by 1. This is because the LocalUserIndexes reject the upgrade if the version is not higher.
This wasn't picked up in testing because we don't apply that same version restriction on the test environment.

Bump Group/Community wasm versions to avoid `VersionNotHigher` error

---

backend/canisters/local_user_index/CHANGELOG.md
backend/canisters/local_user_index/api/src/lib.rs
backend/canisters/local_user_index/impl/src/model/bots_map.rs
backend/canisters/local_user_index/impl/src/updates/c2c_notify_user_index_events.rs
backend/canisters/user_index/CHANGELOG.md
backend/canisters/user_index/impl/src/lifecycle/post_upgrade.rs
backend/canisters/user_index/impl/src/updates/register_bot.rs
backend/canisters/user_index/impl/src/updates/update_bot.rs

This is needed to switch notifications over to being handled by the LocalUserIndexes

Store bot endpoints in LocalUserIndexes

---

frontend/app/src/components/home/proposal/MakeProposalModal.svelte
frontend/openchat-agent/src/services/proposalsBot/proposalsBot.client.ts

This fixes the transfer fees specified when submitting a proposal.
They should be as follows:
1 fee for the approval + 1 fee for the transfer to the ProposalsBot + 1 fee for the transfer to the neuron if required.
So 3 fees in total.

Fix transfer amount when submitting proposal

---

frontend/openchat-agent/src/utils/cachePrimer.ts

Rather than using `delete` to remove items from the pending array it instead uses `splice` so that the array remains contiguous. I've switch the iteration to be backwards so that on average the `splice` only has to move very few (if any) items.

CachePrimer fixes

---

frontend/openchat-agent/src/services/community/community.client.ts

This reverts commit 71d96d9318cb6be33cd488abcfed9def0023c2c6.

Revert "Always save community details in the cache to bump `last_updated` (#7974)"

---

Cargo.lock
Cargo.toml

This will allow us to use `cargo update` to pull in all latest non-breaking version updates

Use single digit to specify dependency versions

---

frontend/app/src/components/home/AcceptRulesModal.svelte
frontend/app/src/components/home/ChannelOrCommunitySummary.svelte
frontend/app/src/components/home/Home.svelte
frontend/app/src/components/home/communities/details/CommunitySummary.svelte
frontend/app/src/components/home/groupdetails/GroupDetailsBody.svelte
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/state/app.svelte.spec.ts
frontend/openchat-client/src/state/app.svelte.ts
frontend/openchat-client/src/state/community/detailUpdates.ts

Since local updates occur on individual collections (e.g. members or blocked users), if makes much more sense to apply these updates at the same scope. Previously if _any_ of the community details had updates all of the derived stores would be re-run. Not a huge cost, but this re-organisation avoids that.

A more efficient approach to community details updates

---

frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/state/app/appStores.spec.ts
frontend/openchat-client/src/state/chat/serverDetails.ts

Prior to this, we would detect that there have been no new updates and so skip setting the store value.
But when you change chat we need to update the store regardless of if there are new updates.

Only skip updating chat details store if chatId matches

---

scripts/deploy-local.sh

The canisterId changed because we removed the LocalGroupIndex and Notifications canisters

Update dev userId to send test tokens to

---

frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/state/app/appStores.spec.ts
frontend/openchat-client/src/state/app/stores.ts
frontend/openchat-client/src/state/utils.ts

After selecting a new chat the route changes, this causes the `selectedChatId` to update, which then triggers the `eventsStore` to be recalculated but the `serverEventsStore` is still holding events for the previous chat.
The `serverEventsStore` then gets updated and the `eventsStore` is calculated again.
As of this PR, we clear the server events store immediately after the selected chat changes, before the events store is recalculated.

Avoid superfluous events computation after changing selected chat

---

backend/canisters/community/impl/src/updates/c2c_update_proposals.rs
backend/canisters/group/impl/src/updates/c2c_update_proposals.rs
backend/canisters/proposals_bot/CHANGELOG.md
backend/libraries/chat_events/src/chat_events.rs

This isn't needed because we now poll for proposal updates whenever a proposal chat is selected.

Avoid marking chat as active if only proposal tally has been updated

---

frontend/app/src/components/home/ChatEvent.svelte
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/state/localUpdates.ts
frontend/openchat-client/src/utils/chat.ts
frontend/openchat-client/src/utils/rtc.ts
frontend/openchat-shared/src/domain/chat/chat.ts
frontend/openchat-shared/src/domain/webrtc/webrtc.ts

The new version of `createMessage` now assigns the event index and message index, so the callers no longer have to.

Simplify how we create new messages

---

frontend/openchat-client/src/utils/media.ts

SVG upload is currently broken because canvas.toBlob does not support the svg mime type. However, we should not be uploading svgs anyway because they are dangerous. The existing `changeDimensions` function already effectively rasterizes the svg, we just need to change the mimeType to png to make it a) work and b) work safely.

Fix SVG upload

---

frontend/app/src/components/home/TextContent.svelte

This irritates me constantly. 
fixes #8336

make the link expander a tiny bit easier to click on mobile

---

backend/canisters/community/CHANGELOG.md
backend/canisters/group/CHANGELOG.md
frontend/app/src/components/UserPill.svelte
frontend/app/src/components/home/ChannelOrCommunityMembers.svelte
frontend/app/src/components/home/ChatEvent.svelte
frontend/app/src/components/home/ChatMessage.svelte
frontend/app/src/components/home/DeletedContent.svelte
frontend/app/src/components/home/MentionPicker.svelte
frontend/app/src/components/home/RepliesTo.svelte
frontend/app/src/components/home/ReplyingTo.svelte
frontend/app/src/components/home/RightPanel.svelte
frontend/app/src/components/home/VideoCallContent.svelte
frontend/app/src/components/home/activity/ActivityEvent.svelte
frontend/app/src/components/home/communities/details/UserGroup.svelte
frontend/app/src/components/home/groupdetails/BlockedUser.svelte
frontend/app/src/components/home/groupdetails/DirectChatDetails.svelte
frontend/app/src/components/home/groupdetails/Member.svelte
frontend/app/src/components/home/groupdetails/Members.svelte
frontend/app/src/components/home/groupdetails/User.svelte
frontend/app/src/components/home/pinned/PinnedMessage.svelte
frontend/app/src/components/home/profile/TransactionEndpoint.svelte
frontend/app/src/components/home/profile/ViewUserProfile.svelte
frontend/app/src/utils/user.ts
frontend/openchat-client/src/openchat.ts

The main change is to modify `getDisplayName` to take the userId, the community members and the webhooks, rather than the user (UserSummary) and the community members.

Make how we retrieve display names consistent

---

frontend/app/src/components/Router.svelte
frontend/openchat-client/src/openchat.ts
frontend/openchat-client/src/state/app/stores.ts
frontend/openchat-shared/src/utils/map.ts

And then fall back to the first chat in the scope if necessary (which is the current behaviour).

Select the last selected chat for scope by default

---

backend/canisters/registry/CHANGELOG.md
backend/canisters/registry/api/can.did
backend/canisters/registry/api/src/lib.rs
backend/canisters/registry/api/src/updates/add_token.rs
backend/integration_tests/src/registry_tests.rs
frontend/app/src/utils/sns.ts
scripts/deploy-test-chat-ledger.sh
scripts/proposals/add_token_to_registry.sh

This is no longer used, we instead call `icrc1_supported_standards`

Remove `token_standard` from token details

---

backend/libraries/types/src/fcm_data.rs
backend/notification_pusher/aws/CHANGELOG.md

Updated the context of the notifications. Group and community are now indicated as a part of the notification.

Updated notification formatting

---

backend/canisters/local_user_index/impl/src/lib.rs
backend/canisters/user_index/CHANGELOG.md
backend/libraries/types/src/fcm_data.rs
backend/libraries/types/src/notifications.rs
backend/notification_pusher/core/src/lib.rs
backend/notification_pusher/core/src/reader.rs
backend/notification_pusher/core/src/user_notifications/processor.rs

Added more data into the FCM data mix, which will provide more control to the native apps over how the notifications are displayed. 
~Snuck in updated android native app dependencies.~
Native app deps update moved to a new PR https://github.com/open-chat-labs/open-chat/pull/8494

Further updates to FCM data

---

frontend/src-tauri/gen/android/app/build.gradle.kts
frontend/src-tauri/gen/android/build.gradle.kts
frontend/src-tauri/gen/android/gradle.properties
frontend/tauri-plugin-oc/android/build.gradle.kts
frontend/tauri-plugin-oc/android/gradle.properties
frontend/tauri-plugin-oc/android/gradle/wrapper/gradle-wrapper.properties
frontend/tauri-plugin-oc/android/settings.gradle

Only relevant for the native app, to reduce noise in the next PR which will add notification management by the app.

Android app dependencies update

---

frontend/app/build_android.sh
frontend/app/build_docker.sh
frontend/src-tauri/gen/android/app/src/main/AndroidManifest.xml
frontend/src-tauri/gen/android/app/src/main/java/com/oc/app/MainActivity.kt
frontend/src-tauri/gen/android/app/src/main/java/com/oc/app/NotificationDismissReceiver.kt
frontend/tauri-plugin-oc/android/src/main/java/IntentsManager.kt
frontend/tauri-plugin-oc/android/src/main/java/NotificationsManager.kt

Native app wouldn't run properly since the build was missing some of the new vars. Also added a bit of code to manage dismissed notifications. Not releasing dismissed notifications caused issues with the summary notification showing incorrect numbers for new messages.

Fix android app build and notification dismissal

---

backend/notification_pusher/core/src/user_notifications/pusher.rs
frontend/tauri-plugin-oc/android/build.gradle.kts
frontend/tauri-plugin-oc/android/src/main/java/NotificationsManager.kt

Notifications pusher will now set the priority for the android notifications to high. On the android side, added priority to the notification when it's created device-side, which may have an effect with some OEMs.

Set notification priority on the server side
