open-chat-labs/open-chat

- frontend/src/utils/caching.ts
This ensures we never overwrite a cached message with an older version.
For example we could receive a message notification, then as we are about to write it to the cache we get an updated version of that message from the canister, without this change we would overwrite the canister event with the now out of date notification event.
> Skip writing message to cache if already exists

- frontend/src/services/common/chatMappers.ts
- frontend/src/services/group/candid/idl.js
- frontend/src/services/group/candid/types.d.ts
- frontend/src/services/groupIndex/candid/types.d.ts
- frontend/src/services/notifications/candid/types.d.ts
- frontend/src/services/user/candid/idl.d.ts
- frontend/src/services/user/candid/idl.js
- frontend/src/services/user/candid/types.d.ts
- frontend/src/services/user/mappers.ts
- frontend/src/services/userIndex/candid/types.d.ts
This will allow us to display SNS transfers on the UI.
> Map the SNS cryptocurrency transfer types

- backend/canisters/user/impl/src/governance_clients/nns.rs
- backend/canisters/user/impl/src/governance_clients/sns.rs
A new subtype has been added to the manage_neuron response which causes the candid deserialization to fail.
This PR adds the new subtype and also makes the code assume everything worked fine if we ever fail to deserialize the response since that is the most likely outcome and otherwise we'll get errors every time a new subtype is added.
> Fix voting on NNS proposals

- frontend/src/services/data/data.client.ts
This fixes the issue of images failing to render after being sent.
> Set `blobUrl` after uploading files

- frontend/src/components/home/ChatMessage.svelte
- frontend/src/components/home/Markdown.svelte
- frontend/src/components/home/TimeAndTicks.svelte
- frontend/src/utils/emojis.ts
> Increase the size of messages containing only a single emoji

- frontend/app/readme.md
I removed one section which was specific to running II locally and also updated the bit about getting ICP for local testing.
> Update frontend readme

- frontend/app/src/components/home/GiphySelector.svelte
> fix giphy selector rendering

- frontend/openchat-client/src/services/serviceContainer.ts
This PR merges `rehydrateEventList` and `rehydrateMissingReplies` into a single `rehydrateEvent` method which now takes one event at a time rather than a list. This covers all of our use cases nicely.
> Simplify how we hydrate events

- frontend/app/package.json
- frontend/app/src/components/home/Markdown.svelte
- frontend/app/src/utils/emojis.ts
- frontend/package-lock.json
If https://github.com/nolanlawson/emoji-picker-element/pull/293 get's merged in we can avoid using a git package reference.
> Make `isSingleEmoji` synchronous

- frontend/app/src/components/home/CryptoTransferBuilder.svelte
making receiver reactive was a mistake!
> fix transfer in group

- backend/canisters/group/impl/src/updates/send_message.rs
`user_being_replied_to` was incorrect for quote replies in threads because the user being replied to was being looked up in the main events list rather than the thread's event list.
> Fix bug where a thread could be linked to an uninvolved user

- frontend/app/rollup.config.js
- frontend/openchat-agent/src/utils/caching.ts
PS - this one is already deployed
> fix the build artefacts and remove possibly controversial db deletion

- frontend/app/src/i18n/cn.json
recreating this PR we received since it's not running for some reason. 
+ plus one additional change I received via DM.
> chinese corrections

- frontend/app/src/components/home/groupdetails/InviteUsers.svelte
- frontend/app/src/components/home/profile/ReferUsers.svelte
makes it easier to invite people if the other person is actually with you.
> add qr codes for sharing urls

- frontend/app/src/components/home/Home.svelte
- frontend/app/src/utils/notifications.ts
- frontend/openchat-client/src/events.ts
- frontend/openchat-client/src/openchat.ts
This depends on the service worker change in this PR
https://github.com/open-ic/oc-landing/pull/19
> Close notifications for msgs that have been read

- frontend/openchat-agent/package.json
- frontend/package.json
- frontend/turbo.json
- scripts/deploy-website-prod-test.sh
- scripts/deploy-website-prod.sh
- scripts/deploy-website-testnet.sh
- scripts/deploy-website-web-test.sh
Bit of a pain in the arse but I think this now works correctly
> Make sure we always build the right version

- backend/canisters/group/impl/src/lifecycle/post_upgrade.rs
Reverts open-ic/open-chat#2641
> Revert "Enable new joiner rewards for the ICP Party group"

- frontend/app/src/components/home/MessageEntry.svelte
- frontend/dev.sh
- frontend/package-lock.json
- frontend/readme.md
- frontend/turbo.json
Still not ideal (yet), but can probably be improved. 
PM2 gives a nice way to manage all the dev tasks together. Basically has the same problem as turborepo, but at least you can see the problem and individually restart the broken project. From then on it works quite smoothly.
> Alternative approach to dev mode

- frontend/app/src/components/Fab.svelte
- frontend/app/src/theme/dark.ts
- frontend/app/src/theme/light.ts
- frontend/app/src/theme/themes.ts
hopefully correct a problem we are seeing on some old phone browsers.
> Design fix

- backend/canisters/user_index/api/can.did
- backend/canisters/user_index/api/src/queries/current_user.rs
- backend/canisters/user_index/impl/src/queries/current_user.rs
Should be deployed after website
> Remove "suspended" field frm current_user response

- frontend/app/src/components/home/Home.svelte
seems to also be necessary on close (to cover the case where the user uses the browser back button
> another tick

- frontend/CHANGELOG.md
- frontend/app/rollup.config.js
found _some_ reports that these have to be non-relative so let's give that a go
> attempt to fix twitter share

- frontend/CHANGELOG.md
- frontend/app/src/components/home/Home.svelte
A previously requested feature.
> make the right panel dismissible (via esc or clicking away)

- frontend/app/src/components/home/Stats.svelte
> make sure crypto messages are reactive

- frontend/openchat-agent/src/services/openchatAgent.ts
this will stop an un-loadable reply context derailing the whole app load.
> small error handling change

- sns/config/sns.yml
@hpeebles you need to give me your real dev principal
> Add small dev neuron & use correct dev principals

- frontend/app/src/components/landingpages/ArchitecturePage.svelte
- frontend/app/src/components/landingpages/BlogPage.svelte
- frontend/app/src/components/landingpages/BlogPostPage.svelte
- frontend/app/src/components/landingpages/Header.svelte
- frontend/app/src/components/landingpages/LandingPage.svelte
- frontend/app/src/components/landingpages/MenuItems.svelte
- frontend/app/src/components/landingpages/MobileMenuItems.svelte
- frontend/app/src/components/landingpages/RoadmapPage.svelte
- frontend/app/src/components/landingpages/WhitepaperPage.svelte
- frontend/app/src/components/landingpages/blog/BlogPost.svelte
- frontend/app/src/components/landingpages/blog/BlogSummary.svelte
- frontend/app/src/components/landingpages/blog/ResponsiveDesign.svelte
- frontend/app/src/components/landingpages/blog/Security.svelte
- frontend/app/src/components/landingpages/blog/posts.ts
- frontend/app/src/routes.ts
- frontend/app/src/styles/mixins.scss
- frontend/app/src/utils/urls.ts
I think this will reasonably easy to maintain. Adding a new post will just be a matter of creating a component with the markup (straight html) and then adding an entry into a dictionary to create a mapping between a slug and the component.
> Add blog section to landing pages

- backend/canisters/group/CHANGELOG.md
- backend/canisters/group/impl/src/lifecycle/post_upgrade.rs
- backend/canisters/group/impl/src/model/participants.rs
This reverts commit d319cb8f94a9ea4c01a3e919d8d9d719557b9d37.
> Revert "Set all `notifications_muted` dates to `now` to fix data inconsistency (#3210)"

- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/landingpages/ArchitecturePage.svelte
- frontend/app/src/components/landingpages/WhitepaperPage.svelte
- frontend/app/src/routes.ts
> fix small routing regression

- frontend/app/src/components/home/Home.svelte
Probably not important, but just on the off-chance that this is contributing to some slightly odd intermittent mobile issues.
> shouldn't be floating the right panel on mobile

- frontend/app/src/components/home/ChatMessage.svelte
- frontend/app/src/components/home/thread/Thread.svelte
1) stop it getting stuck on spinner when initiating a thread
2) prevent race condition with Intersection observer when closing a thread (or any right panel) on mobile
> Couple of small bug fixes

- backend/canisters/proposals_bot/CHANGELOG.md
- canister_commit_ids.json
This needs to be updated and merged when the proposals bot upgrade has executed
> Update proposals_bot post release

- frontend/app/src/components/home/Markdown.svelte
- frontend/openchat-push/src/index.ts
... where we were still using # in the routes
> couple of small routing fixes

- frontend/app/src/components/home/PollBuilder.svelte
if there is a trailing answer, add it automatically to the list of answers to prevent confusion.
fixes #3441
> remove common problem with poll creation

- frontend/app/src/components/App.svelte
- frontend/app/src/utils/logging.ts
- frontend/openchat-agent/src/services/group/candid/idl.js
- frontend/openchat-agent/src/services/group/candid/types.d.ts
- frontend/openchat-agent/src/services/group/group.caching.client.ts
- frontend/openchat-agent/src/services/group/group.client.interface.ts
- frontend/openchat-agent/src/services/group/group.client.ts
- frontend/openchat-agent/src/services/group/mappers.ts
- frontend/openchat-agent/src/services/groupIndex/candid/idl.js
- frontend/openchat-agent/src/services/groupIndex/candid/types.d.ts
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-agent/src/services/userIndex/candid/idl.js
- frontend/openchat-agent/src/services/userIndex/candid/types.d.ts
- frontend/openchat-agent/src/services/userIndex/mappers.ts
- frontend/openchat-agent/src/services/userIndex/userIndex.caching.client.ts
- frontend/openchat-agent/src/services/userIndex/userIndex.client.interface.ts
- frontend/openchat-agent/src/services/userIndex/userIndex.client.ts
- frontend/openchat-client/src/agentWorker.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-shared/src/domain/chat/chat.ts
- frontend/openchat-shared/src/domain/user/user.ts
- frontend/openchat-shared/src/domain/worker.ts
- frontend/openchat-worker/src/worker.ts
This allows a more surgical response rather than freezing / deleting a group. 
Not this will also require a corresponding back end change I think.
> allow platform mod to delete a message

- frontend/app/src/components/home/TextContent.svelte
> fix start time for youtube videos

- frontend/app/src/components/home/MiddlePanel.svelte
- frontend/app/src/components/home/RecommendedGroup.svelte
- frontend/app/src/components/home/RecommendedGroups.svelte
> Small UX improvement joining group from what's hot

- frontend/app/src/components/ModalContent.svelte
- frontend/app/src/components/home/Footer.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/NotificationsBar.svelte
- frontend/app/src/components/home/communities/edit/Edit.svelte
- frontend/app/src/components/home/communities/explore/CommunityCard.svelte
- frontend/app/src/components/home/communities/explore/Explore.svelte
- frontend/app/src/i18n/en.json
- frontend/app/src/i18n/fr.json
- frontend/openchat-agent/src/services/groupIndex/candid/idl.d.ts
- frontend/openchat-agent/src/services/groupIndex/groupIndex.client.ts
- frontend/openchat-agent/src/services/groupIndex/mappers.ts
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-shared/src/domain/search/search.ts
- frontend/openchat-shared/src/domain/worker.ts
- frontend/openchat-worker/src/worker.ts
wire up editing community and move to the new explore_communities end point.
> Edit & explore

- frontend/app/src/components/home/Home.svelte
- frontend/openchat-agent/src/services/common/chatMappers.ts
- frontend/openchat-agent/src/services/common/publicSummaryMapper.ts
- frontend/openchat-agent/src/services/community/mappers.ts
- frontend/openchat-agent/src/services/localUserIndex/mappers.ts
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-agent/src/services/user/mappers.ts
- frontend/openchat-agent/src/utils/caching.ts
- frontend/openchat-client/src/stores/chat.ts
- frontend/openchat-client/src/utils/chat.ts
- frontend/openchat-shared/src/domain/chat/chat.ts
- frontend/openchat-shared/src/domain/response.ts
Got to think about a better way, but this fixes things for now. Unbelievably difficult to track down!
> Fix safari serialisation issues. 

- frontend/app/src/components/home/ChatList.svelte
- frontend/app/src/components/home/ChatSummary.svelte
- frontend/app/src/components/home/CurrentChatMenu.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/RecommendedGroups.svelte
- frontend/app/src/components/home/groupdetails/Members.svelte
- frontend/openchat-agent/src/services/common/chatMappers.ts
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-agent/src/utils/chat.ts
- frontend/openchat-client/src/openchat.ts
> More fixes

- backend/bots/examples/icp_dispenser/impl/src/lifecycle/heartbeat.rs
- backend/bots/examples/satoshi_dice/impl/src/jobs/process_pending_actions.rs
- backend/canisters/group/CHANGELOG.md
- backend/canisters/group/impl/src/new_joiner_rewards.rs
- backend/canisters/local_user_index/api/src/lib.rs
- backend/canisters/local_user_index/impl/src/jobs/make_btc_miami_payments.rs
- backend/canisters/user/CHANGELOG.md
- backend/canisters/user_index/impl/src/jobs/make_pending_payments.rs
- backend/canisters/user_index/impl/src/timer_job_types.rs
- backend/canisters/user_index/impl/src/updates/c2c_notify_events.rs
- backend/libraries/ledger_utils/src/icrc1.rs
- backend/libraries/ledger_utils/src/nns.rs
- backend/libraries/ledger_utils/src/sns.rs
- backend/libraries/types/can.did
- backend/libraries/types/src/cryptocurrency.rs
- upgrade_order.md
This reverts commit 651360558b6dee737497007a07984062b967ea08.
> Revert "Add `ledger` field to completed crypto transactions (#3912)"

- frontend/app/src/components/home/communities/edit/Edit.svelte
- frontend/openchat-client/src/utils/rtc.ts
+ fix web rtc messages in channels
> invite while creating community

- backend/libraries/search/src/lib.rs
Tweaking some search weights to better fit intuition. We really should be using Tantivy - just need to implement stable memory backed [Directory](https://docs.rs/tantivy/0.20.2/tantivy/directory/trait.Directory.html)!
> Improve message search results (pending Tantivy)

- frontend/openchat-client/src/utils/chat.ts
- frontend/openchat-shared/src/utils/chat.ts
this was causing (unnecessary) errors on webtest
> there no need to turn this into an error

- frontend/app/src/components/Panel.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/RightPanel.svelte
- frontend/app/src/components/home/nav/LeftNav.svelte
- frontend/app/src/stores/layout.ts
- frontend/app/src/stores/rightPanel.ts
- frontend/openchat-client/src/openchat.ts
- Show filter in right panel by default if room
- Community filters should disappear if not in explore tab
- If you explore communities the Favourites icon is selected too
- After importing a group it is not in my list of channels
> Few more small bug fixes

- frontend/app/src/components/home/Home.svelte
- frontend/openchat-agent/src/services/common/publicSummaryMapper.ts
- frontend/openchat-agent/src/services/group/group.client.ts
- frontend/openchat-agent/src/services/groupIndex/candid/idl.d.ts
- frontend/openchat-agent/src/services/groupIndex/candid/idl.js
- frontend/openchat-agent/src/services/groupIndex/candid/types.d.ts
- frontend/openchat-agent/src/services/groupIndex/groupIndex.client.ts
- frontend/openchat-agent/src/services/groupIndex/mappers.ts
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-shared/src/domain/chat/chat.ts
- frontend/openchat-shared/src/domain/worker.ts
use the channel lookup and redirect where possible.
> redirect groups -> channels

- frontend/app/src/components/Button.svelte
- frontend/app/src/components/home/PollAnswer.svelte
- frontend/app/src/components/home/PrizeContent.svelte
- frontend/app/src/components/home/TextContent.svelte
- frontend/app/src/components/home/proposals/ProposalVoteButton.svelte
I cannot reproduce the problem this seems to be causing for some, but I think it's serious enough that I should just role back this fix entirely and think again.
> revert hover touch hack

- frontend/openchat-client/src/openchat.ts
> Remove community from preview if a member

- frontend/app/src/components/home/ChatMessage.svelte
- frontend/app/src/components/home/ChatMessageMenu.svelte
- frontend/app/src/components/home/TextContent.svelte
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/stores/chat.ts
- frontend/openchat-client/src/stores/translation.ts
- frontend/openchat-client/src/utils/chat.ts
- frontend/openchat-shared/src/utils/map.ts
> Allow translating more message types

- frontend/app/src/components/home/CryptoSelector.svelte
and reduce vertical padding a bit
> make token drop down scrollable

- frontend/app/package.json
- frontend/app/src/components/home/MemeBuilder.svelte
- frontend/app/src/components/home/MessageActions.svelte
- frontend/openchat-client/src/utils/media.ts
- frontend/package-lock.json
set the `skipInsertMeme` setting
make sure that `fill` is set to false for meme fighter messages.
> upgrade meme fighter

- frontend/app/src/components/landingpages/FeaturesPage.svelte
- frontend/app/src/stores/menu.ts
Make sure that a) they close on scroll and b) they don't disappear off the top of the screen.
> fix menu in landing pages

- frontend/app/src/components/home/profile/UserProfile.svelte
I'd quite like to get this in ahead of your PR so I can push the current state to webtest
> Fix bug in `UserProfile.svelte`

- frontend/app/src/components/UserPill.svelte
- frontend/app/src/theme/dark.ts
I shouldn't have enabled auto-merge on previous PR because this change should have been part of it
> Small color adjustment

- frontend/app/public/.ic-assets.json5
make sure that the stuff in the public directory gets cached as well as the stuff in the build directory.
> ic-assets file for public dir

- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/Markdown.svelte
showing the user profile card when the user mention is clicked is a bit trickier because ideally we would like to align it to the point where the user clicks. We _could_ do it and just pop it up in the middle of the screen easily enough, but I'm going to think about it and see if we can come up with something better.
> open members when everyone is clicked

- frontend/app/src/components/home/GroupPermissionsEditor.svelte
- frontend/app/src/components/home/GroupPermissionsViewer.svelte
- frontend/openchat-agent/src/services/common/chatMappers.ts
- frontend/openchat-agent/src/services/user/candid/idl.d.ts
- frontend/openchat-agent/src/services/user/mappers.ts
This reverts commit 715057fed446ffcf62f3ab93e55f443893d97870.
#	frontend/openchat-agent/src/services/user/candid/idl.d.ts
> Revert "Disable mention_all permission til users upgraded (#4423)"

- backend/canisters/community/CHANGELOG.md
- backend/canisters/community/impl/src/lib.rs
- backend/canisters/community/impl/src/model/channels.rs
- backend/libraries/types/src/group_roles.rs
- frontend/app/src/components/home/GroupPermissionsEditor.svelte
- frontend/app/src/components/home/GroupPermissionsViewer.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/addgroup/NewGroup.svelte
If it's a private community or group then the default permission for @everyone is all members
> All members can @everyone by default in private cxt

- frontend/app/src/components/home/MessageActions.svelte
This reverts commit d3023c4ae82b8fbf389205dfa350058e0278254d.
> Revert "temporarily disable prize messages (#4492)"

- frontend/app/src/components/home/Home.svelte
When a chat is selected it is unarchived
> Don't auto-select an archived chat

- frontend/app/src/components/home/Home.svelte
This was accidentally removed by @julianjelfs PR
https://github.com/open-chat-labs/open-chat/pull/4577
> Put back fix to stop archived chats being selected

- frontend/app/src/components/LinkButton.svelte
- frontend/app/src/components/home/profile/Accounts.svelte
- frontend/app/src/i18n/cn.json
- frontend/app/src/i18n/de.json
- frontend/app/src/i18n/en.json
- frontend/app/src/i18n/es.json
- frontend/app/src/i18n/fr.json
- frontend/app/src/i18n/it.json
- frontend/app/src/i18n/iw.json
- frontend/app/src/i18n/jp.json
- frontend/app/src/i18n/ru.json
- frontend/app/src/i18n/vi.json
- frontend/openchat-shared/src/domain/crypto.ts
This PR has been deployed to prod_test
> Hide/show empty accounts + order by $ balance

- frontend/app/src/components/home/PrizeContent.svelte
- frontend/openchat-push/package.json
- frontend/openchat-worker/package.json
- frontend/turbo.json
Basically make sure that the turbo `typecheck:xxx` commands all depend on `^typecheck`
> Fix turbo build

- frontend/app/src/components/home/nav/LeftNav.svelte
Noticed this wasn't quite working earlier.
> fix highlight selected community

- frontend/app/src/components/OfflineFooter.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/i18n/cn.json
- frontend/app/src/i18n/de.json
- frontend/app/src/i18n/en.json
- frontend/app/src/i18n/es.json
- frontend/app/src/i18n/fr.json
- frontend/app/src/i18n/it.json
- frontend/app/src/i18n/iw.json
- frontend/app/src/i18n/jp.json
- frontend/app/src/i18n/ru.json
- frontend/app/src/i18n/vi.json
- frontend/openchat-client/src/liveState.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/stores/network.ts
This is a first stage. Now that we _know_ when the user is online or offline, we can also take other actions e.g. modify fetch / caching strategies in various places.
> track and inform user when offline

- frontend/openchat-client/src/utils/poller.ts
Pause polling if we lose network connection
> make the poller aware of network status

- frontend/app/src/components/home/communities/edit/Details.svelte
- frontend/app/src/theme/community/windoge98.ts
> few final windoge tweaks

- frontend/app/src/components/Head.svelte
Not sure if setting the canonical tag in this way is going to cut the mustard for google. But let's try it and see.
> see if setting canonical tag dynamically works

- frontend/openchat-shared/src/domain/crypto.ts
> add exchange rates for windoge98 and taggr

- frontend/app/src/components/home/CryptoSelector.svelte
> reduce max height

- frontend/app/src/components/home/CryptoSelector.svelte
- frontend/openchat-shared/src/domain/crypto.ts
bit hacky and I'm not sure why this didn't seem to be a problem before but this seems to work now - deployed to webtest already.
> fix mobile

- frontend/app/src/components/App.svelte
- frontend/app/src/components/Panel.svelte
- frontend/app/src/components/home/CryptoSelector.svelte
- frontend/app/src/components/home/profile/AccountSelector.svelte
- frontend/app/src/styles/mixins.scss
- frontend/app/src/theme/community/windoge98.ts
- frontend/app/src/theme/dark.ts
- frontend/app/src/theme/light.ts
- frontend/app/src/theme/types.ts
This gives theme authors a bit more flexibility. 
Still doesn't support the async loading of custom fonts e.g. google fonts but a bit better.
> control font-family with css vars

- frontend/app/src/components/home/Home.svelte
This is incorrect and should all be being done inside the `Head.svelte` component now.
> remove redundant code

- frontend/app/src/theme/community/windoge98.ts
- frontend/app/src/theme/themes.ts
- frontend/app/src/theme/types.ts
Also settle on a font for windoge98.
> support dynamic loading of web fonts for themes too

- frontend/app/src/components/home/profile/Accounts.svelte
@julianjelfs this was the only remaining change right?
> Use more appropriate theme var

- frontend/app/src/i18n/cn.json
- frontend/app/src/i18n/de.json
- frontend/app/src/i18n/en.json
- frontend/app/src/i18n/es.json
- frontend/app/src/i18n/fr.json
- frontend/app/src/i18n/it.json
- frontend/app/src/i18n/iw.json
- frontend/app/src/i18n/jp.json
- frontend/app/src/i18n/ru.json
- frontend/app/src/i18n/vi.json
This reverts commit af766253016a94c1323b5dbc90a128517f261306.
> Adjust messaging for change of SNS pay gate fee %

- frontend/app/src/components/MultiToggle.svelte
> Stop label wrapping inside MultiToggle component

- frontend/app/src/components/NumberInput.svelte
- frontend/app/src/components/Range.svelte
- frontend/app/src/components/home/PrizeContentBuilder.svelte
> change prize limits and add direct input as well as slider

- frontend/app/src/components/home/MessageActions.svelte
> fix message action reactivity

- frontend/app/.ic-assets.json5
- frontend/app/src/stores/xframe.ts
> support external logout

- frontend/app/src/components/EditLabel.svelte
Mostly about making sure that if the label contains {tokens} then the same tokens are present in the suggested correction.
> Correction validation

- frontend/app/src/components/home/PrizeContentBuilder.svelte
- frontend/app/src/components/home/communities/edit/Edit.svelte
and make sure that we set the lastCryptoSent ledger when sending a prize message.
> fix edit community label

- frontend/app/src/components/NotFound.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/openchat-client/src/openchat.ts
Make sure that we show the not found modal (that already exists) when we are unable to resolve the chat. 
fixes #5156
> Not found modal

- .gitignore
- scripts/make_upgrade_canister_proposal.sh
- scripts/proposals/upgrade_communities.sh
- scripts/proposals/upgrade_cycles_dispenser.sh
- scripts/proposals/upgrade_escrow.sh
- scripts/proposals/upgrade_group_index.sh
- scripts/proposals/upgrade_groups.sh
- scripts/proposals/upgrade_identity.sh
- scripts/proposals/upgrade_local_group_indexes.sh
- scripts/proposals/upgrade_local_user_indexes.sh
- scripts/proposals/upgrade_market_maker.sh
- scripts/proposals/upgrade_neuron_controller.sh
- scripts/proposals/upgrade_notifications.sh
- scripts/proposals/upgrade_notifications_index.sh
- scripts/proposals/upgrade_online_users.sh
- scripts/proposals/upgrade_proposal_validation.sh
- scripts/proposals/upgrade_proposals_bot.sh
- scripts/proposals/upgrade_registry.sh
- scripts/proposals/upgrade_storage_buckets.sh
- scripts/proposals/upgrade_storage_index.sh
- scripts/proposals/upgrade_translations.sh
- scripts/proposals/upgrade_user_index.sh
- scripts/proposals/upgrade_users.sh
- scripts/verify-release.sh
Now you just pass in the CHANGELOG and the rest is built around that.
> Automate building of upgrade proposal summaries

- frontend/app/src/components/home/admin/ReviewTranslationCorrections.svelte
- frontend/app/src/i18n/i18n.ts
Not that sure why this behaves differently but it does.
> change the way locales are loaded and sort by key

- frontend/app/src/components/home/LinkPreviews.svelte
- frontend/app/src/components/home/SpotifyPreview.svelte
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/utils/media.ts
> embed spotify links

- frontend/app/build_dev.sh
- frontend/app/build_prod.sh
- frontend/app/src/components/home/MiddlePanel.svelte
- frontend/app/src/components/home/RightPanel.svelte
- frontend/app/src/components/home/video/ActiveCall.svelte
- frontend/app/src/stores/video.ts
- frontend/app/src/theme/community/barbie.ts
- frontend/app/src/theme/community/halloween.ts
- frontend/app/src/theme/community/signals.ts
- frontend/app/src/theme/community/white.ts
- frontend/app/src/theme/community/windoge98.ts
- frontend/app/src/theme/light.ts
make sure all the main themes look basically ok for video. 
Switch the prod build script over to the prod video bridge instance.
> video updates

- frontend/app/src/components/GooglyEyes.svelte
- frontend/app/src/components/Overlay.svelte
- frontend/app/src/components/home/thread/ThreadHeader.svelte
> close thread with escape

- frontend/app/.ic-assets.json5
- frontend/app/src/stores/xframe.ts
> whitelist a couple more origins

- frontend/app/src/components/home/video/ActiveCall.svelte
- frontend/app/src/stores/video.ts
- frontend/openchat-client/src/openchat.ts
so we can see what is taking the time when starting a call. Seems like it is _mostly_ a front end wait while daily actually starts the call now. 
This also fixes the bug where you try to start a second call which required a page refresh to fix.
> Added some metrics 

- frontend/app/src/components/home/ChatSummary.svelte
> indicate private chats in the chat list

- frontend/app/src/components/home/profile/UserProfile.svelte
> fix toggle id

- backend/canisters/community/CHANGELOG.md
- backend/canisters/community/impl/src/lib.rs
- backend/canisters/group/CHANGELOG.md
- backend/canisters/group/impl/src/lib.rs
- backend/canisters/user/CHANGELOG.md
- backend/canisters/user/impl/src/lib.rs
Reverts open-chat-labs/open-chat#5517
> Revert "Reset `video_call_operators`"

- frontend/app/src/components/App.svelte
- frontend/app/src/components/Router.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/HomeRoute.svelte
- frontend/app/src/components/home/video/IncomingCall.svelte
so that you can navigate to the home page and not trash a running call.
> move everything up a level

- frontend/app/src/components/home/Markdown.svelte
- frontend/app/src/components/home/profile/VideoCallRingtone.svelte
- frontend/app/src/components/home/profile/VideoCallSettings.svelte
- frontend/app/src/stores/video.ts
- frontend/package-lock.json
- frontend/package.json
> Make ringtone selection cooler

- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/utils/chat.ts
> Fix avatar url in profile popup

- frontend/app/src/components/home/video/ActiveBroadcastSummary.svelte
- frontend/app/src/components/home/video/ActiveCall.svelte
- frontend/app/src/stores/video.ts
- frontend/openchat-client/src/openchat.ts
Add a small delay between updating the participant's permissions and sending them a message. Slightly mysterious but this seems to be necessary in some circumstances. 
Also avoid showing the broadcast call banner if you are already in the call.
> Add a small delay

- backend/canisters/identity/CHANGELOG.md
- backend/canisters/identity/impl/src/queries/http_request.rs
- backend/canisters/user_index/CHANGELOG.md
- backend/canisters/user_index/impl/src/queries/http_request.rs
This reverts commit 8ebad83be88923fd862022fb968ae40044e8f875.
> Revert "Add ability to debug user principal migrations (#5750)"

- frontend/app/src/components/landingpages/blog/SignIn.svelte
Oops I shouldn't have enabled auto-merge
> Edits to blog post

- frontend/app/src/components/calendar/Calendar.svelte
- frontend/app/src/components/calendar/utils.ts
- frontend/app/src/components/calendar/weekdays.ts
- frontend/app/src/i18n/i18n.ts
Seems like there isn't a particularly good generic solution for this so easier to just hard code it.
> fix day names and abbreviations

- frontend/app/src/components/App.svelte
- frontend/app/src/components/home/admin/ReviewTranslationCorrections.svelte
- frontend/app/src/i18n/i18n.ts
I _think_ that the lazy loading of other locales was causing the component to get unmounted. So this little hacklet is required.
> fix admin translation loading issue

- frontend/app/src/components/Input.svelte
- frontend/app/src/components/home/admin/OperatorFunctions.svelte
- frontend/openchat-agent/src/services/userIndex/userIndex.client.ts
- frontend/openchat-client/src/openchat.ts
> Admin stuff

- frontend/app/src/components/home/admin/OperatorFunctions.svelte
- frontend/app/src/components/home/profile/Accounts.svelte
> add token enable to admin screen

- frontend/openchat-service-worker/src/cache_plugin.ts
- frontend/openchat-service-worker/src/service_worker.ts
- frontend/package-lock.json
- frontend/package.json
by using a custom workbox plugin which ensures that response code is 200 (like the existing plugin) and also that the response content-type is _not_ text/html
fixes #5966
> Improve cache

- frontend/app/src/components/home/Home.svelte
In ensuring that setSelectedCommunity did not get called twice, I re-introduced the problem that the first channel does not always get selected. This is a fairly hacky solution that solves both things.
> fix small regression

- frontend/app/.ic-assets.json5
- frontend/app/src/stores/xframe.ts
Adding the current ZKP url (https://bxnm7-oqaaa-aaaag-albpq-cai.icp0.io/) to xframe.ts and ic-assets.json .
> Add ZKP to XFrame ancestors

- frontend/app/src/components/home/pinned/PinnedMessage.svelte
- frontend/app/src/styles/mixins.scss
> get rid of gold background on pinned messages

- frontend/app/.ic-assets.json5
- frontend/app/src/stores/xframe.ts
I'm part of the Konecta team and we're creating a gamified pre-registration website. Our aim is that for every achievement we invite people to share on the Konecta OC Community how much time they got into their time capsule. For that, we want to integrate the X-Frame.
[Konecta video](https://www.youtube.com/watch?v=6VoD7cPZhEg)
> chore: add Konecta Pre-register webapp to Frame Ancestors

- frontend/app/.ic-assets.json5
- frontend/app/src/stores/xframe.ts
We're updating our domain to zkpoker.app :)
> Update zkp url to new domain

- frontend/app/src/components/home/ChatSummary.svelte
Another small fix for the white theme
> make sure that the chat menu is visible on mobile

- frontend/app/src/components/home/RepliesTo.svelte
- frontend/app/src/theme/community/white.ts
- frontend/app/src/theme/dark.ts
- frontend/app/src/theme/light.ts
- frontend/app/src/theme/types.ts
don't like the inset replies. This is better.
> improve replies on white

- frontend/app/src/components/home/ChatEventList.svelte
- frontend/app/src/components/home/CurrentChatMessages.svelte
- frontend/app/src/components/home/LinkPreviews.svelte
- frontend/app/src/components/home/thread/Thread.svelte
- frontend/app/src/stores/scrollPos.ts
I want this so that I can toggle the reverse scroll on and off myself on my iphone and get a view on whether it is improved in iOS 18
> allow override of reverse scroll

- frontend/app/src/components/home/Markdown.svelte
- frontend/app/src/components/home/proposals/ProposalContent.svelte
- frontend/app/src/theme/community/blue.ts
- frontend/app/src/theme/community/signals.ts
- frontend/app/src/theme/community/windoge98.ts
- frontend/app/src/theme/defaultDark.ts
- frontend/app/src/theme/defaultLight.ts
- frontend/app/src/theme/types.ts
There doesn't really appear to be any good reason for us even having configurable markdown colours. 
fixes #6515
> Markdown fix

- frontend/app/src/theme/defaultDark.ts
- frontend/app/src/theme/defaultLight.ts
> fix small issue with replies border

- frontend/app/src/components/Hoverable.svelte
- frontend/app/src/components/Progress.svelte
- frontend/app/src/components/home/PollAnswer.svelte
- frontend/app/src/components/home/PollContent.svelte
- frontend/app/src/theme/community/blue.ts
- frontend/app/src/theme/community/signals.ts
- frontend/app/src/theme/community/tokyonight.ts
- frontend/app/src/theme/defaultDark.ts
- frontend/app/src/theme/types.ts
fix poll colours and some alignment regressions.
> Style fixes

- backend/canisters/community/CHANGELOG.md
- backend/canisters/group/CHANGELOG.md
- backend/canisters/user/CHANGELOG.md
- backend/libraries/chat_events/src/chat_events.rs
- backend/libraries/chat_events/src/chat_events_list.rs
This reverts commit c5a9e100850d609d17dc8c2ff145ba7c709209c6.
> Revert "Remove events from being stored on the heap (#6753)"

- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/nav/LeftNav.svelte
> Preserve community list scroll position across routing events

- frontend/app/src/components/home/profile/SwapCrypto.svelte
> Tidy up swap warning

- frontend/app/src/components/home/ChatMessage.svelte
- frontend/app/src/components/home/ChatMessageContent.svelte
- frontend/app/src/components/home/PrizeWinnerContent.svelte
Show the prize winner's profile on click. 
Don't attempt to navigate to the related prize message as a) it doesn't work and b) now that prize winners are all in a thread it doesn't really make any sense.
> improvement to prize winner message

- frontend/app/src/components/calendar/Calendar.svelte
- frontend/app/src/components/calendar/calendarState.svelte.ts
- frontend/app/src/components/home/profile/ChitEvents.svelte
- frontend/app/tsconfig.json
just trying to get more of a feel for svelte 5 patterns and pick off another component along the way.
> convert the calendar to svelte 5

- frontend/app/src/components/home/ChatList.svelte
- frontend/app/src/components/home/ChatSummary.svelte
- frontend/app/src/components/home/CurrentChatHeader.svelte
- frontend/app/src/components/home/InitialGroupMessage.svelte
- frontend/app/src/components/home/RecommendedGroup.svelte
- frontend/app/src/components/home/communities/details/ChannelCard.svelte
- frontend/app/src/components/home/groupdetails/GroupDetailsBody.svelte
- frontend/app/src/components/home/thread/ThreadHeader.svelte
- frontend/app/src/components/home/thread/ThreadPreview.svelte
- frontend/app/src/components/home/video/ActiveCall.svelte
- frontend/app/src/components/home/video/ActiveCallSummary.svelte
- frontend/app/src/components/home/video/IncomingCall.svelte
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-worker/src/worker.ts
Fix multiple scenarios where we transiently show the wrong avatar when joining and previewing groups and channels.
> Fix a few hydration issues

- frontend/app/src/components/App.svelte
I don't think there is any good reason for this restriction now
fixes #6739
> Support guest mode when running in iframe

- frontend/app/src/components/home/nav/LeftNav.svelte
- frontend/openchat-client/src/liveState.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/stores/chat.ts
- frontend/openchat-client/src/stores/global.ts
- frontend/openchat-client/src/stores/localChatSummaryUpdates.ts
- frontend/openchat-shared/src/domain/chat/chat.ts
Previously we were not using the local updates mechanism but rather just updating the global stores which causes inevitable jiggling.
> Improve the way favourites and pinned chats are handled

- frontend/app/src/components/home/Home.svelte
- frontend/app/src/routes.ts
- frontend/openchat-client/src/liveState.ts
- frontend/openchat-client/src/openchat.ts
fixes #6823 
Also fixes adding external channels which is currently broken.
> make sure we switch to default route if we remove the last fav

- frontend/openchat-agent/src/services/localUserIndex/localUserIndex.client.ts
- frontend/openchat-agent/src/utils/mapping.ts
> guard conversion of referral code

- frontend/app/src/components/home/ChatMessage.svelte
- frontend/openchat-client/src/openchat.ts
> whitelist of content types that allow edit

- frontend/app/src/components/App.svelte
- frontend/app/src/components/home/video/ActiveCall.svelte
Not sure how this every worked. Maybe it didn't.
> hide video on landing pages

- frontend/app/src/components/home/ChatMessage.svelte
> remove weird global css

- frontend/app/src/components/home/PrizeContent.svelte
- frontend/app/src/utils/bots.ts
- frontend/openchat-client/src/openchat.ts
And replace with rudimentary mouse event check.
> Revert stack check

- frontend/app/src/components/home/RightPanelWrapper.svelte
> fix verify click with floating right panel

- frontend/app/src/components/bots/BotMessageContext.svelte
- frontend/app/src/components/home/ChatMessage.svelte
- frontend/openchat-agent/src/services/externalBot/externalBot.ts
Make a bit smaller and give a little bit more space.
> More bot message

- frontend/app/src/components/home/communities/explore/Explore.svelte
- frontend/app/src/stores/communityFilters.ts
let's squeeze this in as well
fixes #7110
> fix community explorer

- frontend/app/build_dev.sh
- frontend/app/build_prod.sh
- frontend/app/build_prod_test.sh
- frontend/app/build_testnet.sh
- frontend/app/rollup.config.mjs
- frontend/app/src/components/home/GenericPreview.svelte
uses [this tiny little thing](https://github.com/open-chat-labs/openchat-preview) to load the preview links
> use home grown preview service rather than generic proxy

- frontend/openchat-client/src/utils/builtinBotCommands.ts
This used to be dev only but it shouldn't be any more.
> enable update bot command

- frontend/app/src/components/home/GenericPreview.svelte
> add alt text for image preview

- backend/canisters/registry/api/can.did
- backend/canisters/registry/api/src/main.rs
When running the deploy_local.sh script it gives a candid error which is fixed by the above PR
> Fix local environment setup

- frontend/app/src/components/home/ChatMessage.svelte
- frontend/app/src/components/home/nav/LeftNav.svelte
fix a small regression working out image dimensions after message bubble rejig. 
remove scroll bar in left nav. It's not very useful and looks monstrously bad on windows with a mouse. This is not completely ideal but I think the clear lesser of two evils.
> couple of small ui fixes

- frontend/app/src/components/home/ChatMessage.svelte
- frontend/app/src/components/home/ChatMessageMenu.svelte
- frontend/app/src/utils/devices.ts
Make sure that we don't include things like touch screen laptops when checking for touch devices if we only intend to capture things like phones and tablets.
> fine tune the touch device detection

- frontend/app/src/components/home/ChatSummary.svelte
- frontend/app/src/components/home/CurrentChatHeader.svelte
- frontend/app/src/components/home/InitialGroupMessage.svelte
- frontend/app/src/components/home/RecommendedGroup.svelte
- frontend/app/src/components/home/communities/SelectedCommunityHeader.svelte
- frontend/app/src/components/home/communities/explore/CommunityCard.svelte
- frontend/app/src/components/home/groupdetails/GroupDetailsBody.svelte
- frontend/app/src/components/home/nav/LeftNav.svelte
- frontend/app/src/components/home/nav/LeftNavItem.svelte
- frontend/app/src/components/icons/WithVerifiedBadge.svelte
- frontend/openchat-agent/src/services/externalBot/externalBot.ts
- frontend/openchat-agent/src/services/userIndex/userIndex.client.ts
- frontend/openchat-client/src/openchat.ts
Following user feedback, the feeling was that the tick in the left nav was a bit in your face.
> tone down the tick a bit and remove it from the left nav avatar

- frontend/app/src/components/home/ChatMessageMenu.svelte
A few people have complained about this and I don't really see any reason not to have this universally available.
> always include copy message menu option

- frontend/app/src/components/home/MessageEntry.svelte
This fixes a regression on mobile caused by the direct bot stuff
> Fix return

- frontend/app/src/components/home/DailyChitModal.svelte
Woops... should've included this in the previous PR
> Remove unused CSS

- frontend/app/src/components/Tabs.svelte
- frontend/app/src/components/bots/AutoBotBuilder.svelte
> render tabs dynamically

- frontend/app/src/components/home/Stats.svelte
- frontend/app/src/i18n/ar.json
- frontend/app/src/i18n/cn.json
- frontend/app/src/i18n/de.json
- frontend/app/src/i18n/en.json
- frontend/app/src/i18n/es.json
- frontend/app/src/i18n/fa.json
- frontend/app/src/i18n/fr.json
- frontend/app/src/i18n/hi.json
- frontend/app/src/i18n/it.json
- frontend/app/src/i18n/iw.json
- frontend/app/src/i18n/jp.json
- frontend/app/src/i18n/pl.json
- frontend/app/src/i18n/ru.json
- frontend/app/src/i18n/uk.json
- frontend/app/src/i18n/vi.json
- frontend/openchat-client/src/stores/index.ts
- frontend/openchat-worker/src/worker.ts
> Display minutes online this month in user stats

- frontend/app/package.json
- frontend/app/src/components/DateInput.svelte
- frontend/app/src/components/bots/CommandParamInstance.svelte
- frontend/app/src/components/home/MultiLineInput.svelte
- frontend/app/src/i18n/ar.json
- frontend/app/src/i18n/cn.json
- frontend/app/src/i18n/de.json
- frontend/app/src/i18n/en.json
- frontend/app/src/i18n/es.json
- frontend/app/src/i18n/fa.json
- frontend/app/src/i18n/fr.json
- frontend/app/src/i18n/hi.json
- frontend/app/src/i18n/it.json
- frontend/app/src/i18n/iw.json
- frontend/app/src/i18n/jp.json
- frontend/app/src/i18n/pl.json
- frontend/app/src/i18n/ru.json
- frontend/app/src/i18n/uk.json
- frontend/app/src/i18n/vi.json
- frontend/package-lock.json
- frontend/package.json
Replaced `svelte-datetime-picker` with `svelty-picker` component due to better support for picking time.
Time picker is equivalent in design and functionality to the material design version of it, and should work well for desktop and mobile users.
> Added new DateTime component

- frontend/app/src/components/bots/ApiKey.svelte
- frontend/app/src/components/bots/AutoBotBuilder.svelte
- frontend/app/src/components/bots/BotBuilderModal.svelte
- frontend/app/src/components/bots/BotCommands.svelte
- frontend/app/src/components/bots/BotMessageContext.svelte
- frontend/app/src/components/bots/CommandArg.svelte
- frontend/app/src/components/bots/CommandInstanceBuilder.svelte
- frontend/app/src/components/bots/CommandParameterViewer.svelte
- frontend/app/src/components/bots/CommandViewer.svelte
- frontend/app/src/components/bots/botState.ts
- frontend/app/src/components/bots/install/CaptureSubscribeParams.svelte
- frontend/app/src/components/home/InitialChatMessage.svelte
- frontend/openchat-agent/src/services/common/chatMappersV2.ts
- frontend/openchat-agent/src/services/localUserIndex/localUserIndex.client.ts
- frontend/openchat-agent/src/services/localUserIndex/mappers.ts
- frontend/openchat-agent/src/services/userIndex/mappers.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/stores/chat.ts
- frontend/openchat-client/src/utils/chat.ts
- frontend/openchat-shared/src/domain/bots.ts
- frontend/openchat-shared/src/domain/chat/chat.ts
- frontend/openchat-shared/src/domain/permission.ts
SlashCommand -> Command
ParamInstance -> Arg
Schema -> Definition
Fix the handling of optional command params. 
Make sure that ephemeral messages don't find their way into chat summaries.
> Simplify / harmonise type names

- frontend/app/src/components/bots/WithBotManagement.svelte
- frontend/app/src/components/bots/install/BotInstaller.svelte
Make sure that bots with no commands can be installed properly 
Fix small issue with permissions for generating api keys.
> fix no command scenario

- .github/workflows/docker_release.yaml
- README.md
Only builds a new image if there were new commits to master in the last 24 hours.
> Nightly build OC docker image and push

- frontend/app/src/components/home/DurationPicker.svelte
This looks a bit weird at the moment as there is a select list with only one option.
> disable select if only one duration

- frontend/app/src/components/home/BalanceWithRefresh.svelte
- frontend/app/src/components/home/profile/Accounts.svelte
- frontend/app/src/components/home/profile/AccountsModal.svelte
- frontend/app/src/stores/settings.ts
- frontend/app/src/utils/config.ts
> Toggle to show/hide token balances

- scripts/proposals/set_log_visibility.sh
> Add script to set canister log visibility

- frontend/app/src/components/home/Home.svelte
I think this is the best option for now. No idea what's going on but something in the home page conversion broken the root level modals.
> revert home route conversion

- frontend/app/src/components/App.svelte
- frontend/app/src/components/Avatar.svelte
- frontend/app/src/components/IntegerInput.svelte
- frontend/app/src/components/ModalPage.svelte
- frontend/app/src/components/SelectChatModal.svelte
- frontend/app/src/components/VirtualList.svelte
- frontend/app/src/components/bots/CommandSelector.svelte
- frontend/app/src/components/home/ChatMessage.svelte
- frontend/app/src/components/home/ChatSummary.svelte
- frontend/app/src/components/home/CurrentChat.svelte
- frontend/app/src/components/home/CurrentChatMessages.svelte
- frontend/app/src/components/home/GenericPreview.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/MessageEntry.svelte
- frontend/app/src/components/home/MiddlePanel.svelte
- frontend/app/src/components/home/RightPanel.svelte
- frontend/app/src/components/home/communities/details/ChannelCard.svelte
- frontend/app/src/components/home/communities/details/CommunityDetailsHeader.svelte
- frontend/app/src/components/home/communities/explore/Explore.svelte
- frontend/app/src/components/home/groupdetails/InviteUsersBody.svelte
- frontend/app/src/components/home/video/ActiveCall.svelte
- frontend/app/src/components/home/video/ActiveCallActions.svelte
- frontend/app/src/components/home/video/ActiveCallParticipants.svelte
- frontend/app/src/components/tooltip/Tooltip.svelte
- frontend/app/src/stores/rightPanel.ts
- frontend/app/src/utils/effects.svelte.ts
This allows us to add thresholds on how frequently these effects are allowed to run before we think there is something wrong. 
Helps see hot spots in the reactivity.
> use tracked effects on some of the more sensitive areas

- README.md
Without this things go wrong if there is already state within the local replica.
> Set the `--clean` DFX param when running OC locally

- frontend/openchat-client/package.json
- frontend/openchat-client/src/state/ui.svelte.spec.ts
- frontend/openchat-client/vitest.config.js
- frontend/package-lock.json
It would be very nice to write tests for this stuff as it gets more complicated migrating more state to svelte 5 runes.
> establish a pattern for testing reactive state

- frontend/app/src/components/home/CurrentChatMessages.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/RightPanel.svelte
- frontend/app/src/components/home/RightPanelWrapper.svelte
- frontend/app/src/components/home/pinned/PinnedMessage.svelte
- frontend/app/src/components/home/pinned/PinnedMessages.svelte
The `$effect` in CurrentChatMessages will now take care of this automatically.
> remove some unnecessary wiring

- frontend/app/src/components/home/ChatEventList.svelte
- frontend/app/src/components/home/CurrentChatMessages.svelte
- frontend/openchat-client/src/index.ts
And fix the effect timing for chateventlist
> reinstate userGroupKey

- frontend/app/src/components/home/CurrentChatMessages.svelte
- frontend/app/src/components/home/nav/LeftNav.svelte
- frontend/openchat-client/src/effects.svelte.ts
- frontend/openchat-client/src/liveState.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/state/app.svelte.spec.ts
- frontend/openchat-client/src/state/app.svelte.ts
- frontend/openchat-client/src/state/chat_details/local.svelte.ts
- frontend/openchat-client/src/state/global/local.svelte.ts
- frontend/openchat-client/src/state/set.spec.ts
- frontend/openchat-client/src/state/set.ts
- frontend/openchat-client/src/state/ui.svelte.ts
- frontend/openchat-client/src/stores/chat.ts
- frontend/openchat-client/src/stores/dummyStore.ts
- frontend/openchat-client/src/stores/global.ts
- frontend/openchat-client/src/stores/localChatSummaryUpdates.ts
- frontend/openchat-shared/src/domain/chat/chat.ts
- frontend/openchat-shared/src/domain/index.ts
- frontend/openchat-shared/src/domain/video.ts
> Pinned chats by scope

- frontend/app/src/components/SelectChatModal.svelte
- frontend/app/src/components/bots/DirectChatHeader.svelte
- frontend/app/src/components/bots/InstallationLocationSelector.svelte
- frontend/app/src/components/home/ChatSummary.svelte
- frontend/app/src/components/home/CurrentChatMenu.svelte
- frontend/app/src/components/home/groupdetails/Members.svelte
- frontend/app/src/components/home/nav/LeftNav.svelte
- frontend/openchat-client/src/effects.svelte.ts
- frontend/openchat-client/src/index.ts
- frontend/openchat-client/src/liveState.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/state/app.svelte.ts
- frontend/openchat-client/src/state/chat_details/merged.svelte.ts
- frontend/openchat-client/src/state/community_details/merged.svelte.ts
- frontend/openchat-client/src/state/global/local.svelte.ts
- frontend/openchat-client/src/state/map.ts
- frontend/openchat-client/src/state/set.spec.ts
- frontend/openchat-client/src/state/set.ts
- frontend/openchat-client/src/stores/chat.ts
- frontend/openchat-client/src/stores/global.ts
- frontend/openchat-client/src/stores/localChatSummaryUpdates.ts
- frontend/openchat-client/src/utils/chat.ts
- frontend/openchat-client/src/utils/rtc.ts
- frontend/openchat-shared/src/utils/map.ts
- frontend/openchat-shared/src/utils/set.ts
still requires some temporary sync stores for the moment - but we will get rid of them in due course.
> move global chat state

- backend/canisters/local_group_index/impl/src/jobs/update_controllers.rs
This should've been done within #7871 but I missed it off
> Mark controllers updated once job has completed

- frontend/app/src/components/bots/InstallationLocationSelector.svelte
Seems to actually take between 100 & 150ms so 300 should be enough.
> 100ms is not long enough

- frontend/openchat-client/src/utils/stores.ts
No functional change, just formatting
> Formatting

- .github/workflows/frontend.yaml
- backend/notification_pusher/cli/src/main.rs
- frontend/app/build_dev.sh
- frontend/app/build_docker.sh
- frontend/app/build_mobile.sh
- frontend/app/build_prod.sh
- frontend/app/build_prod_test.sh
- frontend/app/build_testnet.sh
- frontend/app/rollup.config.mjs
- frontend/app/rollup.extras.mjs
- frontend/app/src/components/App.svelte
- frontend/openchat-client/src/config.ts
- frontend/openchat-client/src/openchat.ts
- scripts/run-dev-notification-pusher.sh
I made it use a different VAPID public key when in local dev mode then hard coded the corresponding private key within the `run-dev-notification-pusher.sh` script.
> Add script for running notification pusher locally

- backend/canisters/user/CHANGELOG.md
- backend/canisters/user/impl/src/lifecycle/post_upgrade.rs
- backend/canisters/user/impl/src/model/chit_earned_events.rs
- backend/canisters/user/impl/src/model/streak.rs
Copied from https://github.com/open-chat-labs/open-chat/pull/7703
> Reinstate 1 missed daily claim + notify of change to local timezone

- frontend/app/src/components/MenuIcon.svelte
> small improvement for menu trigger

- frontend/app/src/components/home/Markdown.svelte
- frontend/app/src/styles/global.scss
> slightly nicer theme

- backend/canisters/notifications_index/api/src/queries/fcm_token_exists.rs
- backend/canisters/notifications_index/api/src/updates/add_fcm_token.rs
- backend/canisters/notifications_index/impl/src/queries/fcm_token_exists.rs
- backend/canisters/notifications_index/impl/src/queries/mod.rs
- backend/canisters/notifications_index/impl/src/updates/add_fcm_token.rs
- backend/canisters/notifications_index/impl/src/updates/mod.rs
- backend/canisters/notifications_index/impl/src/updates/push_subscription.rs
- backend/libraries/utils/src/fcm_token_store.rs
- backend/notification_pusher/core/src/lib.rs
- backend/notification_pusher/core/src/user_notifications/processor.rs
- backend/notification_pusher/core/src/user_notifications/pusher.rs
- frontend/app/src/utils/native/notification_channels.ts
- frontend/openchat-agent/src/services/notifications/notifications.client.ts
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-agent/src/typebox.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-shared/src/domain/worker.ts
- frontend/openchat-worker/src/worker.ts
- frontend/tauri-plugin-oc/android/src/main/java/NotificationsHelper.kt
- frontend/tauri-plugin-oc/android/src/main/java/OpenChatPlugin.kt
- frontend/tauri-plugin-oc/build.rs
- frontend/tauri-plugin-oc/guest-js/commands/getFcmToken.ts
- frontend/tauri-plugin-oc/guest-js/index.ts
- frontend/tauri-plugin-oc/permissions/autogenerated/commands/get_fcm_token.toml
- frontend/tauri-plugin-oc/permissions/autogenerated/reference.md
- frontend/tauri-plugin-oc/permissions/default.toml
- frontend/tauri-plugin-oc/permissions/schemas/schema.json
- scripts/run-dev-notification-pusher.sh
Added/fixed functions to check if an FCM token is added for a user. If not, then it is added. Added functions svelte<-> native to check for a FCM token locally on a device.
> Checking existence and assigning FCM tokens to users

- backend/external_canisters/sns_governance/api/src/types.rs
- frontend/app/src/components/landingpages/RoadmapPage.svelte
- frontend/app/src/components/landingpages/blog/AccessGateExpiry.svelte
remove redundant words in comment
> chore: remove redundant words in comment

- frontend/app/src/components/home/CurrentChat.svelte
- frontend/app/src/components/home/CurrentChatHeader.svelte
- frontend/app/src/components/home/CurrentChatMenu.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/RightPanel.svelte
- frontend/app/src/components/home/RightPanelWrapper.svelte
- frontend/app/src/components/home/communities/CommunityMenu.svelte
- frontend/app/src/components/home/communities/SelectedCommunityHeader.svelte
- frontend/app/src/components/home/profile/ViewUserProfile.svelte
- frontend/app/src/components/home/video/ActiveCallActions.svelte
- frontend/openchat-client/src/state/app/stores.ts
- frontend/openchat-client/src/state/ui/stores.ts
- frontend/openchat-client/src/utils/stores.ts
> make sure thread gets closed

- frontend/app/src/components/home/communities/explore/Explore.svelte
> fix load more on community explorer

- frontend/app/src/components/home/CurrentChatHeader.svelte
- frontend/app/src/components/home/CurrentChatMenu.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/SuspendModal.svelte
- frontend/app/src/components/home/profile/ViewUserProfile.svelte
- frontend/openchat-agent/src/services/openchatAgent.ts
- frontend/openchat-agent/src/utils/userCache.ts
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/state/users/state.ts
- frontend/openchat-shared/src/utils/pubsub_events.ts
We were not doing so from the user profile which makes it somewhat easy to suspend someone by mistake. 
Also iron out some issues with local state when suspending and unsuspending. 
fixes #8335
> make sure that we always display the suspend modal

- frontend/app/rollup.extras.mjs
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/mobile/NativeOnboardModal.svelte
- frontend/app/src/i18n/en.json
- frontend/app/vite.config.ts
- frontend/openchat-client/src/utils/androidWebAuthn.ts
- frontend/tauri-plugin-oc/android/src/main/java/commands/PasskeyAuth.kt
Implemented UI for user account linking - it will link an existing user account, with a passkey that will be created for the native app auth.
https://github.com/user-attachments/assets/74b4e8e0-87c8-4ad8-a6b3-cc179a669ef3
> Added UI to link native app with existing accounts

- frontend/app/src/components/home/MiddlePanel.svelte
Not 100% sure this works as I'm having trouble running the video bridge locally, but it certainly won't be worse.
> make sure that the video call alignment fires when right panel is resized

- frontend/app/rollup.extras.mjs
to make sure the CSP is valid in prod mode
> add one wafer thin semi-colon

- frontend/app/src/components/home/access/AccessGateBuilder.svelte
> increase max leaf gates to 10

- frontend/app/rollup.extras.mjs
- frontend/app/src/components/home/InstagramPreview.svelte
- frontend/app/src/components/home/LinkPreviews.svelte
- frontend/openchat-client/src/openchat.ts
- frontend/openchat-client/src/utils/media.ts
> support custom embedding of instagram posts

- frontend/app/src/components/ModalContent.svelte
- frontend/app/src/components/home/Home.svelte
- frontend/app/src/components/home/profile/ViewUserProfileModal.svelte
Profile modal positioning needs to be deferred until the profile data has loaded otherwise we end up with the wrong dimensions and hence the wrong position.
> make sure profile modal is positioned correctly

- backend/canisters/community/impl/src/lifecycle/post_upgrade.rs
This reverts commit 8f0d5eb2a53dc060c9b7f646ec5c244cdee6e70a.
> Revert "Promote designated user to owner of biz community (#8539)"

- frontend/component-lib/src/components/LatestMessage.svelte
- frontend/component-lib/src/components/User.svelte
- frontend/component-lib/src/components/buttons/CommonButton.svelte
- frontend/component-lib/src/index.ts
- frontend/component-lib/src/theme/colour.ts
- frontend/component-test/src/App.svelte
- frontend/component-test/src/BigButtons.svelte
- frontend/component-test/src/BottomBars.svelte
- frontend/component-test/src/Buttons.svelte
- frontend/component-test/src/ChatSummaries.svelte
- frontend/component-test/src/CommonButtons.svelte
- frontend/component-test/src/DebugEvent.svelte
- frontend/component-test/src/Users.svelte
Standardised the debug on the test page a bit.
> User row & updated common button to include small text variant
